### ISSUE TITLE
Drop node 0.6 support

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/raven-node#100]
Does anybody care about this still? By dropping support, I mean, I'd remove automated tests from being run against 0.6. I assume things will continue to work, but I won't be aware of something does break it.

It's causing the build to fail on Travis and I don't personally care to try and fix it.

See: https://travis-ci.org/getsentry/raven-node/jobs/42419289

**Comment by krise3k** [comment]
+1 for dropping and adding support for 0.12

**Comment by connor4312** [comment]
and iojs!
