### ISSUE TITLE
There is no way to provide a custom SSL certificat for HTTPS

### ISSUE THREAD

**Issue by BlackYoup** [getsentry/raven-node#108]
Hi there,

I'm trying to use raven using an HTTPS DSN with a self signed certificate. So, I'm getting a SELF_SIGNED_CERT_IN_CHAIN error when I try to emit messages to sentry.

Is there a way to add ``ca`` field to requests options ? http://nodejs.org/api/https.html#https_https_request_options_callback

I can try to make a PR but not sure about how to correctly give the arguments to the ``transport.send()`` method

Thanks !

**Comment by mattrobenolt** [comment]
Hmm, if you wanna take a stab, I'm ok with that, if not I'll look into this later in the week and see how I can do this.

**Comment by mattrobenolt** [comment]
Fixed with #110

**Comment by BlackYoup** [comment]
Thanks :)
