### ISSUE TITLE
Document kwargs

### ISSUE THREAD

**Issue by kevinburkeshyp** [getsentry/raven-node#109]
It looks like there's an example of the options you can pass to captureError [here](https://github.com/getsentry/raven-node/blob/master/bin/raven#L45), would be nice if they were formally specified/enumerated somewhere.

**Comment by kevinburkeshyp** [comment]
Any update here?

**Comment by andrewtamura** [comment]
See the Sentry docs for client JSON attributes https://docs.getsentry.com/hosted/clientdev/attributes/

Some of the kwargs map directly to the sentry JSON attributes. Other kwargs are translated by the client, e.g. the `request` property in the seen [line 50](https://github.com/getsentry/raven-node/blob/master/bin/raven#L50)

**Comment by benvinegar** [comment]
This is now in the docs [here](https://docs.getsentry.com/hosted/clients/node/usage/#optional-attributes) (added in 910e88cb9a1ace59f6798a52bc41ca7f74ec8cd9).
