### ISSUE TITLE
domain is not defined

### ISSUE THREAD

**Issue by dhritzkiv** [getsentry/raven-node#120]
In `lib/middleware/connect.js`, `domain` isn't defined and a `ReferenceError` is thrown. It appears that it's not available as a global, and must be `require`'d.

v0.8.0 on io.js 2.3.0

**Comment by mattrobenolt** [comment]
Ugh. One sec. Fixing.

**Comment by mattrobenolt** [comment]
@dhritzkiv Sorry about that, 0.8.1 pushed.
