### ISSUE TITLE
Provide integration for console.error

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-node#121]

**Comment by bradvogel** [comment]
+1

**Comment by wearhere** [comment]
+1

**Comment by andrewtamura** [comment]
+1

**Comment by kiwiholmberg** [comment]
Expected this (console.error() stuff)  to be logged by default.

**Comment by benvinegar** [comment]
If possible, we're going to see if this can be logged as a breadcrumb instead.

**Comment by VinceOPS** [comment]
+1

**Comment by LewisJEllis** [comment]
This is now done as a breadcrumb.

**Comment by wearhere** [comment]
So a `console.error` call will only be logged to Sentry if `raven-js` is later told to capture something?

**Comment by LewisJEllis** [comment]
If `raven-node` is told to capture something, to be precise, but yes; breadcrumbs are collected throughout execution (but not immediately reported), and then reported alongside a later captured exception. If you want to report a message immediately, you can `Raven.captureMessage`.
