### ISSUE TITLE
Express/Connect Middleware Documentation is Sparse

### ISSUE THREAD

**Issue by samholmes** [getsentry/raven-node#122]
I had to read the source code to get an idea for how the middleware works and how it should be used. I don't think this is very helpful or explicit enough, and I do think that developers are going to want to know what the middleware does for both Express and Connect.

For example, it wasn't explained that if an error has a status code less than 500, that `errorHandler` wont log it to Sentry. This is important information to know about the middleware. Also, it could be suggested that one could still use `next(err)` for errors that you wouldn't want logged (such as user related errors; invalid input from the user). Would be very useful to know.

Also, it would be helpful to know what `requestHandler` does and why it is required. It is useful to know  that it wraps your routes in a domain, and delegates errors captured in the domain to `errorHandler`. Also, how does this effect the use of `patchGlobal()`?

**Comment by mattrobenolt** [comment]
> For example, it wasn't explained that if an error has a status code less than 500, that errorHandler wont log it to Sentry.

Anything less than a 500 is not an error. `errorHandler` is a middleware so it's always called. It's up to the middleware then to determine if it should pass or do something with it. In our case, we want to intercept errors, which are 5xxs.

> Also, it could be suggested that one could still use next(err) for errors that you wouldn't want logged (such as user related errors; invalid input from the user). Would be very useful to know.

Can you explain this more? I'm not sure the use case or how this would work. I'm not personally very familiar with Connect and Express.

> Also, it would be helpful to know what requestHandler does and why it is required. 

It's not technically required since `domain` objects are optional. But the idea is that we can wrap the entire request cycle in an error domain which captures exceptions more effectively.

> Also, how does this effect the use of patchGlobal()

It shouldn't at all. They can be used together.

**Comment by samholmes** [comment]
# 1
The point about 500 status code is that it should be explained in the docs that `errorHandler` works this way. If devs are unaware about how this middleware uses statusCode/status_code on their error objects, then they might wonder why they're errors aren't being logged when they use these properties for their own purposes.

# 2
To explain more about the second point: If users are aware that the middleware wont log errors with statusCodes < 500, then a user can use this to their advantage if they want to respond to a request that has an error and display a message to the user, but doesn't want to log the error. For example, a user might have invalid input in a POST request, so tell the user what went wrong, but don't log the error.

# 3
If it's not technically required, the docs should be clear about that. Right now the docs say: 

```js
// Should be the first item listed
app.use(raven.middleware.express.requestHandler('{{ SENTRY_DSN }}'));
```

"Should be first item listed" makes me think that it's required. If it's not, then why should it be first item, what does it do, how should I use it, etc?

**Comment by mattrobenolt** [comment]
> The point about 500 status code is that it should be explained in the docs that errorHandler works this way. If devs are unaware about how this middleware uses statusCode/status_code on their error objects, then they might wonder why they're errors aren't being logged when they use these properties for their own purposes.

I guess this is a point of confusion for me. I'd argue that if you're wanting to log an error like that, then the middleware is not for you. A middleware is intended to capture uncaught exceptions. Not the general way to just report errors. You'd use the client directly to log an error that you've captured yourself.

Is that reasonable? Or is there a pattern that I'm misunderstanding that people implement? I'd need to see some code examples since this is unfamiliar to me.

**Comment by billinghamj** [comment]
In Express, it is standard practice to hand off any kind of errors to the middleware by doing `next(error)`- this isn't just for 500 errors.

I had expected that all requests would be logged to Sentry, even if they succeeded.

**Comment by samholmes** [comment]
@mattrobenolt 

>I'd argue that if you're wanting to log an error like that, then the middleware is not for you.

But how would I know that the middleware is not for me if I don't know what the middleware does. Having documentation about the middleware would help me make a decision on whether to use it. Does it make sense why it would be important to explain/document what the middleware does (which is what this issue is really about)?

**Comment by yellowiscool** [comment]
I confirm the documentation could be improved on this part. I tried many things and the raven express middleware still doesn't report my server errors (captureMessage works).

A working express server example would help a lot I think.

**Comment by dcramer** [comment]
I've improved this a bit, but we might want to do more. For now I want to close this out, but feel free to send PRs as we're actively trying to improve this.

**Comment by peter-mouland** [comment]
has anyone got an example of the above working in the correct way?

I'm confused; it sounds like i should respond with 500, but not throw the error using next??

i.e. can someone help with the following:

*server.js*
```javascript
import express from "express";
import routes from "../shared/routes";
import raven from 'raven';

const app = express();

const SENTRY_DSN = 'https://' + process.env.RAVEN_KEY + ': ' + process.env.RAVEN_SECRET + '@app.getsentry.com/' + process.env.RAVEN_APP_ID
const client = new raven.Client(SENTRY_DSN);
raven.patchGlobal(client);
function onError(err, req, res, next) {
  // The error id is attached to `res.sentry` to be returned
  // and optionally displayed to the user for support.
  res.statusCode = 500;
  res.end(res.sentry+'\n');
}
// The request handler be the first item
app.use(raven.middleware.express.requestHandler(SENTRY_DSN));

// The error handler must be before any other error middleware
app.use(raven.middleware.express.errorHandler(SENTRY_DSN));
// Optional fallthrough error handler
app.use(onError);


app.use('/api/v0', routes);

```
*routes.js*
```javascript
import express from 'express';
let router = express.Router();

router.get('/routeExample', (req, res, next) => {

   fnReturnsAPromise({uuid: req.params.uuid})
        .then((data) => {
            res.locals.data =data;
            next();
        })
        .catch((err) => {
            res.status(500);
           next(err)
        })
});

export default router;
```
