### ISSUE TITLE
Update package version after merge #123

### ISSUE THREAD

**Issue by maxvipon** [getsentry/raven-node#124]
Pull #123

**Comment by maxvipon** [comment]
ping

**Comment by xBajci** [comment]
+1.

**Comment by joaocunha** [comment]
Hate to :+1: but a package version update is long due in this case.

**Comment by mattrobenolt** [comment]
Oh, I could have sworn I did this.

Hold on. :)

**Comment by mattrobenolt** [comment]
0.9.0 has been pushed to npm. Sorry about that. :(

**Comment by joaocunha** [comment]
Thank you very much for the timely response, @mattrobenolt! Really enjoying Sentry so far.

**Comment by xBajci** [comment]
Thank you!
