### ISSUE TITLE
not webpack compatibile 

### ISSUE THREAD

**Issue by goldensunliu** [getsentry/raven-node#126]
trying to pack require('raven') using webpack. It seems to break on:
https://github.com/getsentry/raven-node/blob/master/lib/client.js#L10

webpack output is:
```
error given was: Error: Cannot find module "../package.json"```

**Comment by mattrobenolt** [comment]
Hey @goldensunliu, what's your use case here?

It seems like you want to be using https://github.com/getsentry/raven-js instead? raven-node is designed explicitly for running inside a node application and is not compatible with browsers.

**Comment by goldensunliu** [comment]
We are using webpack to do both node and browser side bundling. In this case, I have an entry point which bundles a server/node bundle using webpack including the node-version of raven.

**Comment by mattrobenolt** [comment]
Interesting. Do you have any pointers for how to make this work? I've never used webpack on the server, and frankly, this is the first time hearing of it. :)

**Comment by mattrobenolt** [comment]
I assume something like this? https://github.com/webpack/json-loader Litearlly no idea here. :confused:

**Comment by goldensunliu** [comment]
nice.
```
module.exports = {
    context: __dirname,
    entry: "./index.js", //entry point
    module: {
        loaders: [
            {
                test: /\.json$/,
                loader: "json-loader" 
            }
        ]
    }
}
```
seems to do the trick. thanks!

**Comment by mattrobenolt** [comment]
orly
