### ISSUE TITLE
Add documentation for popular frameworks

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-node#128]
- [x] http://koajs.com/

**Comment by dcramer** [comment]
We need to explore if we're missing anything of relevance.

**Comment by DamonGant** [comment]
I'd have liked to have the info from #146 in the express/connect docs.

**Comment by benvinegar** [comment]
[Sails.js](http://sailsjs.org/)

**Comment by simonepri** [comment]
[Restify](https://github.com/restify/node-restify)
Is almost equal to Express.

**Comment by damongant** [comment]
The stuff from my previous comment should be included at your earliest convenience. I've seen this stuff happen way too much (people calling `setUserContext`, everything works in dev because lack of parallelism, race conditions on prod)

**Comment by kamilogorek** [comment]
Sails.js and Loopback has been added. Restify is almost exactly same as Express.js, and I think people using are are aware of it, so it's be a little tedious.
Also `dataCallback` is already mentioned in the `config` section of the docs.

Closing this one. Please create separate issues if there are any frameworks missing.
