### ISSUE TITLE
Documentation inconsistency: captureException() and captureError() used interchangeably

### ISSUE THREAD

**Issue by bradvogel** [getsentry/raven-node#129]
`captureException()` used on https://docs.getsentry.com/hosted/clients/node/ and `captureError()` used on https://docs.getsentry.com/hosted/clients/node/usage/

Even though they're aliased, it'd be nice if the docs just used `captureException()` consistently, like the JS client docs do -https://docs.getsentry.com/hosted/clients/javascript/usage/

**Comment by benvinegar** [comment]
5b9aa469e548afc5d2498780e522f9be2a35b605

Thanks for pointing this out, Chad. 🍻

**Comment by bradvogel** [comment]
Chad? :)
