### ISSUE TITLE
Implement proper context

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/raven-node#134]
See: #133 

raven-node has no concept of context like the other clients.

We need to expose `userContext`, `tagsContext`, `extraContext`, etc. along with the ability to clear. Then this can work for the middleware to clear after each request finish.

**Comment by diequeiroz** [comment]
:+1:

**Comment by gillesdemey** [comment]
:+1:

**Comment by jdrake** [comment]
:+1: :100:

**Comment by bcallaars** [comment]
:+1:

**Comment by diegopamio** [comment]
:+1: :100:

**Comment by diegopamio** [comment]
It's not included in any release yet, is it?

**Comment by benvinegar** [comment]
@diegopamio – I just published [0.10.0](https://github.com/getsentry/raven-node/releases/tag/0.10.0) to npm.
