### ISSUE TITLE
Express documentation unclear comments

### ISSUE THREAD

**Issue by joshuajabbour** [getsentry/raven-node#135]
There's a typo in the [Express docs](https://github.com/getsentry/raven-node/blob/master/docs/integrations/express.rst) that says

    // The request handler be the first item

I assume that should be `The request handler **must** be the first item`, but even then it's still unclear. Should it be the first registered middleware _at all_, or just registered before `raven.middleware.express.errorHandler`?

**Comment by mattrobenolt** [comment]
Definitely missing "must" there.

Ideally, it's the first registered middleware at all, since you want to capture all errors. If there was an exception that got thrown from a middleware that wasn't wrapped, we wouldn't capture it. :)
