### ISSUE TITLE
Documentation: middleware out of order?

### ISSUE THREAD

**Issue by bradvogel** [getsentry/raven-node#137]
In example https://docs.getsentry.com/hosted/clients/node/integrations/express/, the `requestHandler` middleware is installed after `app.get` is called, despite the comment saying "request handler must be the first item".

Shouldn't the order be this?

```
// The request handler must be the first item
app.use(raven.middleware.express.requestHandler('{{ SENTRY_DSN }}'));

app.get('/', function mainHandler(req, res) {
    throw new Error('Broke!');
});

// The error handler must be before any other error middleware
app.use(raven.middleware.express.errorHandler('{{ SENTRY_DSN }}'));
```

**Comment by mattrobenolt** [comment]
Yeah, you're correct. Will fix. :) Thanks.
