### ISSUE TITLE
Provide context to raven's express integration

### ISSUE THREAD

**Issue by kylehotchkiss** [getsentry/raven-node#139]
Is it possible I could provide additional request context via raven's express integration by adding user data to `req`?

I'm looking to [do something similar to Raven-js' `setUserContext`](https://docs.getsentry.com/hosted/learn/context/) in middleware like

```app.use(function( req, res, next ) { req.UserContextForSentry = x });```

Figured you guys might have a variable in `req` I could add stuff too that will send to sentry in errors.

**Comment by benvinegar** [comment]
@kylehotchkiss – I'm firing up a bunch of raven-node work this week. I'm hoping to have this in place shortly.

**Comment by kylehotchkiss** [comment]
@benvinegar you rock. I appreciate it.

**Comment by benvinegar** [comment]
We've just published [version 0.10.0](https://github.com/getsentry/raven-node/releases/tag/0.10.0), which adds `setUserContext`.

I'm putting together docs now, but it has the [same API as raven-js](https://docs.getsentry.com/hosted/clients/javascript/#adding-context).
