### ISSUE TITLE
Unable to Resolve Module Zlib from Client.js

### ISSUE THREAD

**Issue by Emibob** [getsentry/raven-node#145]
Hi - I'm getting an error that `zlib` is not resolved in `node_modules/raven/lib/client/js`. I see it's being required into `client.js` on line 4, however I do not see it in raven's `node_modules` or `package.json`. Would love some insight into this error, thanks!

![screen shot 2016-02-29 at 5 23 23 pm](https://cloud.githubusercontent.com/assets/4623303/13410972/9f2d50e6-df08-11e5-8e3b-c1b985b772f1.png)

**Comment by mattrobenolt** [comment]
`zlib` is a part of the stadard library in node: https://nodejs.org/api/zlib.html

Based on this, it looks like you're using React Native, and if so, you'd want to use raven-js: https://docs.getsentry.com/hosted/clients/javascript/integrations/react-native/

**Comment by Emibob** [comment]
thanks @mattrobenolt

**Comment by anuraghkp1** [comment]
Use this package to get zlib in react native package https://www.npmjs.com/package/react-zlib-js
