### ISSUE TITLE
Is it possible to call setUserContext using express middleware?

### ISSUE THREAD

**Issue by aburkut** [getsentry/raven-node#146]
Is it possible to call setUserContext using express middleware?

**Comment by DamonGant** [comment]
Yes. Check out how the middleware is instantiated:

https://github.com/getsentry/raven-node/blob/master/lib/middleware/connect.js#L14

This code works:

    var raven = new Raven.Client("<dsn>", {release: "<version>"});
    raven.setUserContext({});
    app.use(Raven.middleware.express.requestHandler(raven));

However, the user context _is not request specific_, so you should not use it with express. Try `dataCallback`. instead:

https://docs.getsentry.com/hosted/clients/node/config/#optional-settings

Note that this callback is _not asyncronous_, so you need to prepare the user context and attach it to the request (which you probably already do anyway) before the error.

**Comment by aburkut** [comment]
Ok, thanks.

**Comment by elliot-a** [comment]
Has anyone got this to work? 

I am adding user data to the req object in express as shown in this short example below : 

```
var raven = new Raven.Client( config.SENTRY_DSN, {
    dataCallback: function(data) {
        console.log(data.request.user.name); // undefined
        return data;}
});

app.get('/example', addUserData, function (req, res) {
    throw new Error('Broke!');
});

app.use(Raven.middleware.express.errorHandler(raven));

function addUserData(req, res, next){
    req.user = { name:'john', id:'1' }
    next();
}
```

However none of that user data seems to present on 'data' object that is passed into 'dataCallback' function. It seems more like the raw request before my custom middleware has added stuff to the object.

Am I missing obvious something here, is there another way of passing user data to Sentry?

Thanks guys!

**Comment by vladikoff** [comment]
This should probably be added to https://docs.sentry.io/clients/node/integrations/express/ page
