### ISSUE TITLE
ExpressJs res.sendFile gave error "no such file or directory ", but error is not captured by sentry

### ISSUE THREAD

**Issue by lukaszewczak** [getsentry/raven-node#148]
Hi, I try to integrate sentry with my express.js app but I came to one situation when error was not captured by sentry.
I made a simple app to show this, below I put the code. 
```
var app = require('express')();
var raven = require('raven');

function onError(err, req, res, next) {
    // The error id is attached to `res.sentry` to be returned
    // and optionally displayed to the user for support.
    res.statusCode = 500;
    res.end(err +'\n'+ res.sentry + '\n');
}

// The request handler must be the first item
app.use(raven.middleware.express.requestHandler('sentry-dsn'));

app.get('/', function mainHandler(req, res) {
    //error id is attached to res.sentry
    throw new Error('Broke!');
});

app.get('/invalid-file-path', function mainHandler(req, res) {
    //error id is attached to res.sentry
    res.sendFile('test1.txt');
});

app.get('/invalid-file', function mainHandler(req, res) {
    //res.sentry is undefined
    res.sendFile(__dirname + '/test-invalid.txt');
});

app.get('/ok-file', function mainHandler(req, res) {
    res.sendFile(__dirname + '/test.txt');
});

// The error handler must be before any other error middleware
app.use(raven.middleware.express.errorHandler('sentry_dsn'));

// Optional fallthrough error handler
app.use(onError);

app.listen(3000);
```
I used this versions: ` "express": "^4.13.4",`, and `"raven": "^0.10.0"`.

When I go to routes `/` or `/invalid-file-path`, everythink is ok, I got the error id attached to `res.sentry`, but when go to route `/invalid-file` `re.sentry` is undefined.

Is it me doing something wrong or is this realy a bug?

**Comment by DamonGant** [comment]
This is not how express error handling works. You need to call next with the error as your first argument, not throw it.

Check out [this article](http://derickbailey.com/2014/09/06/proper-error-handling-in-expressjs-route-handlers/).

**Comment by lukaszewczak** [comment]
This is not mine real app I just made a example app based on sentry example for [ExpressJs](https://docs.getsentry.com/hosted/clients/node/integrations/express/). Error is directly throw just to check if the error is corectly captured by Sentry. Sentry deal with this situation correctly, but the problem is with code in `res.sendFile(__dirname + '/test-invalid.txt');` becouse it is not captured by sentry middleware.

**Comment by DamonGant** [comment]
Somewhere down the line `statusCode: 404` and `status: 404` are added to the error object. Everything below 500 is ignored by the express/connect error handler.

getsentry/raven-node/blob/master/lib/middleware/connect.js#L16

**Comment by lukaszewczak** [comment]
Thank you @DamonGant for explanation. I will close this issue now.
