### ISSUE TITLE
Middleware: Levels based on HTTP code

### ISSUE THREAD

**Issue by bedeoverend** [getsentry/raven-node#149]
I'm using the express middleware to automatically fire off errors, however I was wondering if there was a way to customise the level based on the HTTP code? For example, if it's a 5xx, it should definitely be an `error`, however if for my use case, things like a 4xx should be a `warning`, or even an `info`. Would an optional callback to modify the error be a possibility?

**Comment by DamonGant** [comment]
You could always write your own version of the express middleware handler, found here:

https://github.com/getsentry/raven-node/blob/master/lib/middleware/connect.js

The default is to discard errors below 500.

**Comment by kamilogorek** [comment]
This issue has been closed due to over a year of inactivity. If anyone feels that it should be reopened, please feel free to reopen it and letting me know. Thanks.
