### ISSUE TITLE
Add fetch_git_sha in raven-node

### ISSUE THREAD

**Issue by cancan101** [getsentry/raven-node#150]
Add a function like [`fetch_git_sha` from raven-python](https://github.com/getsentry/raven-python/blob/ed91eef804eb1453ca625270fe1b67e2b687b89b/raven/versioning.py) to the raven-node library.

**Comment by benvinegar** [comment]
Better yet, let's document how to use an existing package like [git-rev](https://www.npmjs.com/package/git-rev) to set the release value in the raven-node docs.

**Comment by kamilogorek** [comment]
Addressed in https://github.com/getsentry/raven-node/pull/382
