### ISSUE TITLE
lsmod issue / TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by arabold** [getsentry/raven-node#152]
I've just created a pull request for lsmod that fixes an issue in raven if no modules are loaded. I would appreciate if raven could update its dependencies once that pull request is merged. Thank you.

https://github.com/defunctzombie/node-lsmod/pull/2

**Comment by arabold** [comment]
defunctzombie has updated [lsmod](https://github.com/defunctzombie/node-lsmod/) to 1.0.0 which fixes this bug. I've created a minimal pull request to update `lsmod`.

**Comment by mattrobenolt** [comment]
Fixed with https://github.com/getsentry/raven-node/pull/154
