### ISSUE TITLE
parseRequest modified global process.env

### ISSUE THREAD

**Issue by LinusU** [getsentry/raven-node#158]
https://github.com/getsentry/raven-node/blob/master/lib/parsers.js#L164

Since http.env is only a reference to process.env, and not a copy of it, it will modify the global env object

**Comment by DamonGant** [comment]
Good catch. This'll need a fix asap to fix some nasty race conditions.

**Comment by benvinegar** [comment]
We no longer pass `process.env` as of dceeb27
