### ISSUE TITLE
How to add user data to the error object in express

### ISSUE THREAD

**Issue by elliot-a** [getsentry/raven-node#160]
I am adding user data to the req object in express as shown in this simplified example below. I am then using the dataCallback function to check to see if the user data has been added and it doesn't look like it has.

```
var raven = new Raven.Client( config.SENTRY_DSN, {
    dataCallback: function(data) {
        console.log(data.request.user.name); // undefined
        return data;}
});

app.get('/example', addUserData, function (req, res) {
    throw new Error('Broke!');
});

app.use(Raven.middleware.express.errorHandler(raven));

function addUserData(req, res, next){
    req.user = { name:'john', id:'1' }
    next();
}
```

However none of that user data seems to present on 'data' object that is passed into 'dataCallback' function. It seems more like the raw request before my custom middleware has added stuff to the object.

Am I missing obvious something here, is there another way of passing user data to Sentry in express? Do you have an example anywhere?

Thanks guys!

**Comment by benvinegar** [comment]
Hi @elliot-a – sorry for the slow reply.

Setting context right now in an express app isn't straight forward. I'm going to look at some solutions this week.

**Comment by vineethawal** [comment]
Hi @benvinegar, you guys giving any thoughts on this?

**Comment by benvinegar** [comment]
@elliot-a, @vineethawal – Quick question, is it reasonable to just tell Express users, "just set `req.user`"? And then have the middleware take that and set the proper user context? If so, I can make that change to the request parser.

**Comment by vineethawal** [comment]
@benvinegar sounds fine 👍

**Comment by chemitaxis** [comment]
Hi! Is this avalaible right now? Thanks!

**Comment by kamilogorek** [comment]
@chemitaxis yes :)

**Comment by kamilogorek** [comment]
@surdu user is extracted from the request later down the road - https://github.com/getsentry/raven-node/blob/ea192886e0e4c6f2ffe982ebbfa30a73885c2c55/lib/parsers.js#L129-L155

I wonder if this is skipped when `request` object is created correctly here - https://github.com/getsentry/raven-node/blob/ea192886e0e4c6f2ffe982ebbfa30a73885c2c55/lib/client.js#L256-L260

Can you provide non-working example that I could use to reproduce the issue?
