### ISSUE TITLE
this._enabled check could be done earlier

### ISSUE THREAD

**Issue by francisdb** [getsentry/raven-node#161]
I was wondering why the enabled check is not done earlier.
https://github.com/getsentry/raven-node/blob/master/lib/client.js#L111

Since only the ident is returned I don't see any use in performing all these other operations?

**Comment by mattrobenolt** [comment]
I'm pretty sure my reasoning was so that the `dataCallback` would be executed and basically everything gets executed as if it were to send, except bails out at the last second.

Is there an issue you're having with this behavior?

**Comment by francisdb** [comment]
can live with that, thanks for explaining
