### ISSUE TITLE
Provide Loopback middleware

### ISSUE THREAD

**Issue by benvinegar** [getsentry/raven-node#162]
https://loopback.io/

**Comment by mattrobenolt** [comment]
What's the compatibility issue with just using the Connect middlewares? If I understand, this is just building on top of Express.

**Comment by benvinegar** [comment]
I don't know yet. But people have tried that and are having difficulty: https://groups.google.com/forum/#!topic/loopbackjs/Mvq5snzKXGs

**Comment by cspeer** [comment]
Yes, I have tried to put the `.use` call to the middleware almost anywhere in the `server.js` without any luck. I haven't dug deeper though yet.
The only thing I found out is that the error handler in express:
```javascript
app.use(function(error, request, response, next) {});
```

in loopback never gets called

**Comment by mattrobenolt** [comment]
Looks like you'd need to do this? https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Error-handlingmiddleware

**Comment by cspeer** [comment]
Maybe. It states "Use error-handling middleware to deal with request errors." which got me confused, because the errors we are talking about here aren't request errors. Or my definition of request errors is wrong.

**Comment by cspeer** [comment]
I just tried it and no this apparently only get's invoked when there is a real request (as in http?) error. If I burry some bad code in my application and run it, my middleware wouldn't get invoked.

**Comment by mattrobenolt** [comment]
Yeah, definitely. The middleware is for capturing uncaught exceptions in the request/response flow. Typically something that'd get bubbled up as a 500 error.

But if you're catching and handling errors yourself (or other libraries) the middleware here won't be too useful. You could always use `client.captureException(err)` yourself explicitly.

**Comment by cspeer** [comment]
I'm about to implement your suggestion. Quick question though:
How does `client. patchGlobal()` work in regards to Promises? Is this going to catch uncaught ES6 rejections?

**Comment by mattrobenolt** [comment]
We do not handle uncaught promise rejections.

@benvinegar did we have a stance on this for raven-js?

**Comment by cspeer** [comment]
Well, I just built a test case and I'm not sure whether `bluebird` is responsible here or not, but my unhandled rejection got reported to sentry

**Comment by mattrobenolt** [comment]
Maybe it in turn triggers the `uncaughtException` signal?

We just hook into it here: https://github.com/getsentry/raven-node/blob/master/lib/client.js#L238

**Comment by cspeer** [comment]
Well, I don't know, but as long as it works (and it works great with sentry) I'm satisfied!

**Comment by benvinegar** [comment]
You can add a hook for unhandled promise rejections in node. See: https://nodejs.org/api/process.html#process_event_unhandledrejection

Should look something like this:

```javascript
process.on('unhandledRejection', function (reason) {
  ravenClient.captureException(reason);
});
```

**Comment by cspeer** [comment]
Thanks @benvinegar 
But it's apparently already taken care of. Like I said Sentry is already receiving unhandled rejections. It's probably `bluebird` that somehow intercepts these errors and bubbles them up to a higher level where Sentry is able to catch them.

Thanks a lot for your help @benvinegar & @mattrobenolt

**Comment by cspeer** [comment]
I found that actually the error handling middleware as described in the [docs](https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Error-handlingmiddleware) never really gets invoked. However, this method described [here](https://docs.strongloop.com/display/public/LB/Environment-specific+configuration#Environment-specificconfiguration-CustomizingRESTerrorhandling) luckily gets invoked every single time there is an error. So, all you actually gotta do besides the obvious Sentry nodejs integration, is to hook into this method and report the emitted error manually to sentry:

```javascript
sentryClient.captureException(error);
```

It works perfectly now! So I would consider this matter as closed :)

**Comment by Freundschaft** [comment]
from what I can read here: 
* https://gist.github.com/pulkitsinghal/82e659ca4b56bc1b4b2c
* https://docs.strongloop.com/display/public/LB/Environment-specific+configuration#Environment-specificconfiguration-CustomizingRESTerrorhandling

as far as I understand the following should be working?

create config.[env].js, e.g. config.production.js

paste the following

```
var raven = require('raven');

module.exports = {
  remoting: {
    errorHandler: {
      handler: raven.middleware.express.errorHandler('DSN')
    }
  }
};

```

at least thats what works for me. the issue with the final handler of the middleware is that only 404 errors will end up there and raven-node by defaul tonly logs errors > 500

Can someone verify that this is the preferred way to do it?

Cheers

**Comment by jesperbruunhansen** [comment]
Hey guys, I just want to share a way I made Sentry tracking work with Loopback 3.

Create a the following middleware handler at `server/middleware/sentry.js`

```js
const Raven = require("raven");
Raven.config("__DSN__").install();

module.exports = () => Raven.errorHandler();
```

Then add the following in `server/middleware.json`

```json
"final": {
    "./middleware/sentry": {}
}
```

Hope this helps someone!

**Comment by kamilogorek** [comment]
Thanks for sharing @jesperbruunhansen! Included it in docs.

**Comment by ohwillie** [comment]
@kamilogorek a fix for the Loopback docs: they should mention that you need to switch to disable Loopback's built-in error handling, and that you should switch to `strong-error-handler`. This isn't an issue for Loopback 3.x, but if you're on Loopback 2.x LTS, Raven's error handler won't actually get called unless you disable the built-in error handling. Details are here: https://loopback.io/doc/en/lb2/Using-strong-error-handler.html

**Comment by kamilogorek** [comment]
Thanks, @ohwillie! Would love to include those things in the docs if you'd find a short moment to create a PR :)
