### ISSUE TITLE
Error objects in extra don't have essential properties

### ISSUE THREAD

**Issue by pornel** [getsentry/raven-node#171]
▶️ [moved from https://github.com/getsentry/raven-js/issues/607]

In JS `Error` objects' `message`, `name`, and `stack` properties are non-enumerable and don't appear when you serialize them:

``` js
JSON.stringify(Error("message was here"))
```

> `{}`

This means that if I put any errors in Raven's `extra` field, I'm going to see an empty object in Sentry.

This is a big obstacle for me, because node application I'm working on wraps all real errors in higher-level user-friendly errors like this:

``` js
try { doWork(); }
catch(realError) {
   const userFriendlyError = new Error("Sorry, internal error");
   userFriendlyError.reason = realError; // raven is unable to serialize this! 
   throw userFriendlyError; // This will be caught by raven
}
```

so with this in Sentry I'm seeing `"Sorry, internal error"` and Additional Data `reason: {}`. I would expect `reason: {message: "…", name: "…", stack: "…"}` etc. extracted manually from the `Error` object.

**Comment by benvinegar** [comment]
So, are you thinking basically a more intelligent object serializer, rather than `JSON.stringify`?

**Comment by pornel** [comment]
Yes. I've been using this previously, and it worked great:

https://github.com/ftlabs/js-abbreviate

**Comment by kamilogorek** [comment]
Addressed in https://github.com/getsentry/raven-node/pull/376

**Comment by kamilogorek** [comment]
@pornel fixed
