### ISSUE TITLE
Needs to truncate frames / work with minified node code

### ISSUE THREAD

**Issue by benvinegar** [getsentry/raven-node#175]
We have reports of users using a framework, [qooxdoo](http://qooxdoo.org/), which minifies entire node applications into a single line of code. If an error throws from that line, we get frame values that include super long lines, resulting in a giant error payloads that trigger "413: Request Entity Too Large" error responses from Sentry.

**Comment by kamilogorek** [comment]
Already fixed. See https://github.com/getsentry/raven-node/issues/153
