### ISSUE TITLE
Include message or title for caught error

### ISSUE THREAD

**Issue by nuflowx** [getsentry/raven-node#186]
So I have

```
client.captureException(data, {
  level: 'error',
  message: msg,
});
```

The message get's passed on to the log on sentry, but unfortunately my title of the error is still only all the data passed on.

![screen shot 2016-08-08 at 16 01 58](https://cloud.githubusercontent.com/assets/17532211/17484398/83081318-5d81-11e6-916c-5aa1fa4d1370.png)

Instead of the `{"request":{"host": [...]}, [...]}`, I'd like to provide a title for that error.

I'm sending a stringified JSON object including the request and such. I'd actually like to provide a title and include the JSON data when you open the error.

Hope this is kind of clear, I think it should be an easy fix and I'm just passing things wrong...

**Comment by benvinegar** [comment]
You should use `captureMessage`. And your extra data should be passed as `extra`:

```javascript
Raven.captureMessage(msg, {
  extra: raw_data // un-stringified
});
```

May I ask why you're doing this? Is this an inbound HTTP request (e.g. received by Express), or an external HTTP request (e.g. to an external HTTP API)?

**Comment by nuflowx** [comment]
I don't really recall what request it was tbh. I'd guess it was sent via an API to the getsentry-site. There you'd have a list of captures on the site itself.

The logs were coming from different errors and using the website-list I couldn't easily tell were the log was coming from, therefor I thought maybe adding a title instead would help.

It's not necessarily relevant for me any more, or at least for now though.

**Comment by kamilogorek** [comment]
Closing due to OP saying this issue is irrelevant anymore.
