### ISSUE TITLE
Original error information is lost, if the error is an object

### ISSUE THREAD

**Issue by romanbsd** [getsentry/raven-node#187]
We have just installed raven in our express app, and we're seeing errors like [Object object].
The reason for that, is the original error is an object, and in
https://github.com/getsentry/raven-node/blob/master/lib/client.js#L154
it's converted to an Error to get the stack-trace. Perhaps it's better to do new Error(JSON.stringify(err)) ?

**Comment by eoinmurray** [comment]
This is an issue for us too, since very often in node errors are given in callbacks as objects.

**Comment by eoinmurray** [comment]
This is a workaround for me

```javascript
function CustomError(error) {
  this.name = error.name
  this.message = (error.message || '')
  this.stack = error.stack
}
CustomError.prototype = Error.prototype;
```

since we have errors coming from a child_process so it contains a name, message and stack...
we just use

```javascript
// using patchGlobal
child_process.on('error', error => {
   throw new CustomError(error)
})
```

or 

```javascript
// using captureException
child_process.on('error', error => {
   raven.captureException(new CustomError(error))
})
```

**Comment by romanbsd** [comment]
Our workaround is having another error middleware before Raven, which converts the object to error.

**Comment by benvinegar** [comment]
> This is an issue for us too, since very often in node errors are given in callbacks as objects.

Can you give me an example? Are these found in built-in libraries like `fs`? Or some popular 3rd-party libraries?

If you are capturing errors manually, it's intended that you pass an actual error object. But if libraries outside of your control are doing this, then maybe we can come up with a compromise.

**Comment by eoinmurray** [comment]
One example is using an RPC from a child process -> if an error is returned over some RPC protocol, it would generally be serialised in some way. 

But perhaps thats a niche issue, and not general enough to be handled by the library.

**Comment by keithhalterman** [comment]
We built [auto-trace](https://github.com/CanopyTax/auto-trace) to solve this problem.

```js
function wrapObjectWithError(err) {
	if (err instanceof Error) {
		return err;
	} else {
		if (typeof err === "string"){
			errOut.message = err;
		}
		else {
			errOut.message = JSON.stringify(err);
		}
		return errOut
	}
}
```

**Comment by kamilogorek** [comment]
It's hard to predict what would be the shape of thrown object, and doing `new Error(JSON.stringify(err))` can end up as a really messy error message.

I'd say that because of that, it shouldn't be handled by the SDK, but rather it's user.
We need a really specific use-case if we'd want to integrate this into our codebase.
Without providing such, I think we should keep it as is.

Thoughts @getsentry/javascript?

**Comment by mitsuhiko** [comment]
@kamilogorek i really don't know but I ran into the same issue just a few days ago.

**Comment by kamilogorek** [comment]
Since there are several workarounds for this issue, I'll close this one for now due to old issues cleanup. Feel free to open a new issue/reopen if it's still relevant. Thanks.

**Comment by Ghazgkull** [comment]
This is the most serious issue I've seen as a Raven client. By capturing "[Object object]", Raven is actually causing **harm** to applications. People use Raven as a way of surfacing errors... but in this case it's actually making errors harder to debug by obscuring useful information. I would suggest that this issue be reopened until a solution can be found.

**Comment by kamilogorek** [comment]
@Ghazgkull thanks for the input. We discussed how to handle it today, and I'll try to write a proper serializer for this use case and modify our UI to handle this if necessary. I'll keep you posted.
