### ISSUE TITLE
Add option to not send currently loaded modules

### ISSUE THREAD

**Issue by nunofgs** [getsentry/raven-node#188]
Can we make [this](https://github.com/getsentry/raven-node/blob/master/lib/client.js#L79) –_modules_ payload optional?

**Comment by kamilogorek** [comment]
Why would you like to do that in the first place? It's very useful information.

**Comment by nunofgs** [comment]
The main issue was with hitting the payload size limit (HTTP 413).

Also, in a big project the module list is rather large and, in my opinion, unnecessary when dependencies are locked.

**Comment by benvinegar** [comment]
How many modules are you sending?

**Comment by nunofgs** [comment]
The largest project currently sends 340+ modules.

**Comment by benvinegar** [comment]
Hm, yeah, that's problematic. I think a better solution is that we internally cap it internally at 100 or something (people shouldn't have to debug this / enable this config option on their own, it should just work).

I assume we're also sending every submodule ... I wonder if there's a clever way of determining what's a top-level module (e.g. parsing package.json on startup?).

**Comment by nunofgs** [comment]
> I think a better solution is that we internally cap it internally at 100 or something

Why not just make it a flag, and default to enabled?

Personally I believe the feature would lose its usefulness if it was displaying just 100 dependencies.

**Comment by kamilogorek** [comment]
@nunofgs because the more flags/options we add, the more we have to support in the future.

Your usecase is already achievable by using `dataCallback`

```js
dataCallback (data) {
  delete data.modules
  return data
}
```

**Comment by benvinegar** [comment]
> Why not just make it a flag, and default to enabled?

Raven/Sentry should try to be as useful as possible, out of the box. If we can find a way to pass modules when it's safe to do so, we should. I still think attempting to separate top-level modules from subdependencies is the way to go; I seriously doubt you have declared 340 packages in `package.json`.

**Comment by oliviertassinari** [comment]
I will use the following diff, it looks good. Let's save some ressource. Sending the modules is pointless when there are locked and versioned.
```diff
   if (SENTRY_DSN) {
-    Raven.config(SENTRY_DSN).install();
+    Raven.config(SENTRY_DSN, {
+        environment: process.env.NODE_ENV || 'development',
+        dataCallback(data) {
+            delete data.modules;
+            return data;
+        }
+    }).install();
     app.use(Raven.requestHandler());
   }
```

**Comment by kamilogorek** [comment]
I'm closing this issue due to the main issue being already solvable.

**Comment by oliviertassinari** [comment]
> I seriously doubt you have declared 340 packages in package.json.

@benvinegar We have 140 declared packages for a 3 people projects. You can easily go beyond 200 packages with a mono repository strategy and a dozen of developers.
