### ISSUE TITLE
Add breadcrumbs

### ISSUE THREAD

**Issue by ehfeng** [getsentry/raven-node#190]
Include breadcrumbs in node client.

Also, reach out to Alexei at Uber (ask @ehfeng to do this) to update him, once this is done.

**Comment by benvinegar** [comment]
I'd explore a version of this where breadcrumbs can be stored on the request object.

**Comment by MaxBittker** [comment]
@LewisJEllis should we reach out to him with the beta?

**Comment by LewisJEllis** [comment]
The current beta doesn't actually have breadcrumbs (that branch is still a bit of a mess), but once it does, yes.

**Comment by LewisJEllis** [comment]
Done, available in 1.1.x (1.1.1 as of writing).
