### ISSUE TITLE
Explore Express/Connect middleware configuration w/o requestHandler

### ISSUE THREAD

**Issue by benvinegar** [getsentry/raven-node#192]
Having to specify both `requestHandler` and `errorHandler` middleware can be confusing for new Sentry users. The more steps that we can reduce, the better.

See if there's a way we can get away with just `errorHandler`.

**Comment by LewisJEllis** [comment]
Researched express/domains/CLS/asynclistener/zones/event loop instrumentation and determined that this is *possible* but hard/tricky.

The instrumentation/monkeypatching to pull this off would also give us more capabilities (deeper tracing, profiling, etc), but we don't have a use for those right now, and by the time we do (if ever) there might be official zone/async_hook APIs to help out, so I'm going to file this under "more work than it's worth".

**Comment by benvinegar** [comment]
_Nods_.
