### ISSUE TITLE
Pass `request` object as 2nd argument to `dataCallback`

### ISSUE THREAD

**Issue by benvinegar** [getsentry/raven-node#194]
If present, we should pass the Express/Connect `request` (or `req`) object as a 2nd argument to `dataCallback` (which, at the moment, only takes `data`). This allows people to further mutate the data payload according to any values that may have been stored on the request object (e.g. user).

Alternatively, explore having the middleware initialization accept a callback argument where this can be done.

See: #93

**Comment by zwily** [comment]
It's been a couple years since a few of us submitted pull requests to get similar functionality in. It would be great to finally have it in the official release. I'm getting tired of using my ancient fork. :smile:

**Comment by LewisJEllis** [comment]
Quick holdover update: I *think* you should be able to use the new context stuff coming soon for this use case. I'll double check and try to provide an example after we publish the 1.0 beta, and if it turns out that you can't, I'll try to address that before we call it stable.

**Comment by zwily** [comment]
Thanks! I'll try it out when context lands.

**Comment by LewisJEllis** [comment]
This use case was resolved in #310. No need to manually parse stuff in dataCallback, just passing a `req` property in either captureException or context will automatically parse the request and any user context found on it, so that'll already be on the `data` obj by the time you hit `dataCallback`.
