### ISSUE TITLE
fingerprint for Express middleware

### ISSUE THREAD

**Issue by jmredfern** [getsentry/raven-node#199]
We are querying external API services and creating Errors based on the results - so the stacktrace is always the same. These are being reported by the Express middleware into a single group. Is there any plans to support fingerprinting via this middleware?

Thanks!

https://docs.sentry.io/hosted/learn/rollups/

**Comment by LewisJEllis** [comment]
Hmm, I see the difficulty you're getting at. You could roll your own via the lower-level `captureException` method, but that sort of defeats the usefulness of the express middleware. We can investigate supporting this use case.

From your user-perspective, how are you imagining communicating your custom fingerprint array? The most immediate way that comes to my mind is via a property added to your `Error` object, but there are other ways it could work - potential new API methods, some state added to the req object, maybe others.

**Comment by kamilogorek** [comment]
Ping @jmredfern. Is this still relevant for you?

**Comment by kamilogorek** [comment]
Closed due to inactivity. Please feel free to reopen if it's still relevant.
