### ISSUE TITLE
Add a shouldSendData Callback

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/raven-node#202]
We should support a similar configuration as for the raven-js setup where we allow events not to be sent based on a callback.

**Comment by LewisJEllis** [comment]
Yep, we basically just copy [this](https://github.com/getsentry/raven-js/blob/3e0877a4f0d48026e64724dfaf234ea1a12b97d1/src/raven.js#L540-L553) over and then call it when appropriate.

**Comment by ibigbug** [comment]
Need this feature. Is there any timeline when will this feature get integrated? I found raven-python also has this feature: https://github.com/getsentry/raven-python/blob/c46f17727d4b980e55e4813082f1dbce3d3ab7bd/raven/base.py#L786

**Comment by ibigbug** [comment]
Cool

**Comment by LewisJEllis** [comment]
Addressed by #220

**Comment by adamreisnz** [comment]
So is this in? It's still not documented in the [documentation](https://docs.sentry.io/clients/node/config/).
