### ISSUE TITLE
Error tracking doesn't work with bodyParser package

### ISSUE THREAD

**Issue by glockjt** [getsentry/raven-node#204]
I have the middleware set up as demonstrated in the documentation for an express app.  However I need to use bodyParser for my app and when I use that, raven error handling doesn't work.  When I remove bodyParser it works.  I believe it has something to do with the error handling in the bodyParser package.  Is there any way to work around this or to get the two packages to play nice together?

**Comment by LewisJEllis** [comment]
Having reviewed bodyParser's docs and implementation, I don't think there should be an issue here; can you give an example snippet?

**Comment by glockjt** [comment]
This was my fault, problem with my own error handling.
