### ISSUE TITLE
Cannot find module 'pg-native'

### ISSUE THREAD

**Issue by ashnamuh** [getsentry/raven-node#210]
I wanted to attach a sentry on the nodejs server that use the Express. So i looked at the [manual](https://docs.sentry.io/clients/node/integrations/express/) and followed. but the following error occurred. What's the problem? I'm using the Express `v4.13.4`, node `v4.4.2`.

![image](https://cloud.githubusercontent.com/assets/14067417/18980389/9fa32ba0-870e-11e6-8987-62515cf9d1b2.png)

app.js:
```
const express = require('express');
const raven = require('raven');

const app = express();
const sentryDSN = 'myDSN';
const client = new raven.Client(sentryDSN);

app.use(raven.middleware.express.requestHandler(sentryDSN));

/*
my middlewares section
*/

app.use(raven.middleware.express.errorHandler(sentryDSN));

app.use(handleResponse); // fallthrough error handler
```

**Comment by ashnamuh** [comment]
sorry. It's something by my mistake

**Comment by ashnamuh** [comment]
Sorry. It's my mistake.

**Comment by seromenho** [comment]
@ashnamuh can you let us know what was your mistake?
Thanks

**Comment by Aea** [comment]
For those coming from a google search and encountering this error, raven appears to be unable to handle a sequelize model as the request.user object. The simplest workaround is to use parseUser in the configuration (see https://docs.sentry.io/clients/node/config/) with a function to extract the parameters you want.
