### ISSUE TITLE
when a user is logined through the redis session, an error occurred

### ISSUE THREAD

**Issue by ashnamuh** [getsentry/raven-node#212]
related #210 

I'm using nodejs server with express. I wanted to attach a sentry on the server to trace some errors. So i looked at the [manual](https://docs.sentry.io/clients/node/integrations/express/) and followed. But the following error occurred. I had thought the error is my mistake. But i found the error occurred when a user is logined through the redis session. What's the problem? I'm using the Express `v4.13.4`, node `v4.4.2` and npm `v3.10.8`. I need your help!

![image](https://cloud.githubusercontent.com/assets/14067417/19228812/ab0ed58c-8f03-11e6-8260-a82fe9ef3c7e.png)

my app configuration:
```
const express = require('express');
const expressSession = require('express-session');
const raven = require('raven');

const app = express();

app.use(expressSession({
  secret: appConfig.sessionSecret,
  resave: false,
  saveUninitialized: false,
  store: new RedisStore({pass: appConfig.redisPass})
}));

app.use(raven.middleware.express.requestHandler(appConfig.sentryDSN));

/*
middlewares: routes, passport, etc.
*/

app.use(raven.middleware.express.errorHandler(appConfig.sentryDSN));

app.use(handleResponse); // fallthrough error handler
```

If i clean up the `RedisStore` line, Raven is working right. But login is not available.

**Comment by mattrobenolt** [comment]
What makes you think this is related to Sentry? The error seems pretty clear that it's unrelated and seems that you're missing `pg-native` which is required by your application.

**Comment by ashnamuh** [comment]
But my application don't require `pg-native`. Is it other npm module error?

**Comment by mattrobenolt** [comment]
I can only assume so, that module isn't used by this project.

**Comment by ashnamuh** [comment]
Thanks for your so kind and fast comment.
The error occurred on [the line](https://github.com/getsentry/raven-node/blob/master/lib/client.js#L122).
Maybe it is error of `json-stringify-safe`?

**Comment by mattrobenolt** [comment]
No, that has 0 dependencies: https://github.com/isaacs/json-stringify-safe/blob/master/package.json

It's coming from `node_modules/pg`. Nothing in `raven-node` has any dependencies on postgres or any libraries that would depend on postgres. It looks directly like your project is using `pg`. So I'd start there.

**Comment by ashnamuh** [comment]
Okay, thanks. It is not related to Sentry. But i'm wondering why happen the error after attach Raven.

**Comment by LewisJEllis** [comment]
Can you provide a more complete code example, with all your imports included? It looks like`RedisStore` is not imported anywhere in the example you provided.

Also, here you're `use`ing `expressSession` first; have you tried `use`ing `raven.middleware.express.requestHandler` first instead, as our documentation suggests [here](https://docs.sentry.io/clients/node/integrations/express/)?

**Comment by ashnamuh** [comment]
Thanks LewisJEllis. See following code example. This is my complete code example. Stupidly, i forgot writing the RedisStore import line in the example.

app.js:
```js
'use strict';

const _ = require('lodash');
const appConfig = require('./config/loader').load('app');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const cors = require('cors');
const express = require('express');
const expressSession = require('express-session');
const FilesystemBackend = require('i18next-node-fs-backend');
const generatorHandler = require('./lib/generator-handler');
const handleResponse = require('./middlewares/handle-response');
const mode = require('./lib/mode');
const passport = require('passport');
const passportMiddleware = require('./middlewares/passport');
const path = require('path');
const RedisStore = require('connect-redis')(expressSession);
const raven = require('raven');
const redisConfig = require('./config/loader').load('redis');
const uploadDir = require('./lib/upload-dir');
const urlRoutes = require('./urls');

const app = express();

app.use(raven.middleware.express.requestHandler(appConfig.sentryDSN));
app.use(cors({
  origin: appConfig.corsOrigin,
  credentials: true
}));
app.use(cookieParser());
app.use(expressSession({
  secret: appConfig.sessionSecret,
  resave: false,
  saveUninitialized: false,
  store: new RedisStore({pass: appConfig.redisPass})
}));
app.use(bodyParser.json());

// It is also not working
// app.use(raven.middleware.express.requestHandler(appConfig.sentryDSN));

passport.serializeUser(passportMiddleware.serializeUser);
passport.deserializeUser(passportMiddleware.deserializeUser);
passport.use(passportMiddleware.localStrategy);
passport.use(passportMiddleware.facebookStrategy);
app.use(passport.initialize());
app.use(passport.session());

// add routes
const addHandler = (method, url, controller) => {
  const handler = controller[method];
  if (!handler) {
    return;
  }

  let middlewares;
  let requestHandler;

  if (_.isArray(handler)) {
    middlewares = _.dropRight(handler);
    requestHandler = generatorHandler(_.last(handler));
  } else if (_.isFunction(handler)) {
    middlewares = [];
    requestHandler = generatorHandler(handler);
  }

  app[method].apply(app, [url].concat(middlewares).concat(requestHandler));
};

urlRoutes.forEach(route => {
  const url = route[0];
  const controller = route[1];
  ['get', 'post', 'put', 'delete', 'head', 'option']
    .forEach(method => addHandler(method, url, controller));
});

app.use(raven.middleware.express.errorHandler(appConfig.sentryDSN));
app.use(handleResponse);

module.exports = app;
```


handle-response.js:
```js
'use strict';


let client = new raven.Client(appConfig.sentryDSN);

module.exports = (error, expressReq, expressRes, next) => {
  // if it's an unexpected error
  expressRes.statusCode = 500;
  expressRes.end(expressRes.sentry + '\n');
  return;
};
```

**Comment by ashnamuh** [comment]
after I saw the error: `Cannot find module 'pg-native'`, i tried to look for why happen the error in the raven code. Additionally, even though i installed 'pg-native' module, following error occurred after a minute. It look like happen in circular stringification of `json-stringify-safe`

![image](https://cloud.githubusercontent.com/assets/14067417/19257032/594bbfc2-8fa7-11e6-80b9-8e8330542f8e.png)

**Comment by LewisJEllis** [comment]
There's definitely something going on here, but to be clear, there's absolutely no way that raven-node or any of its dependencies are attempting to `require('pg-native')`. There has to be some other strange interaction going on here, possibly something along the lines of sequelize/sequelize#3781. This makes every bit of extra code in the reproduction example even more of a liability to investigate; can you try to reduce this to the smallest possible example that still reproduces the problem?

If you can cut out any of the dependencies, middlewares, and abstractions/patterns present in this code that aren't necessary to reproduce the bug and reduce it to a single file that I can run by itself after `npm install`ing some dependencies, then I'd be able to investigate in more detail, but I can't go bug hunting through an entire project.

**Comment by ashnamuh** [comment]
Thank you for being so considerate. I sent an email with my project code to [your email]
(me@lewisjellis.com). You can go bug hunting through the entire project. However, there is korean language in the project such as README, commit, comment. Because i'm Korean.

1. tried `find node_modules -name package.json | xargs grep '"pg-native":'`:
![image](https://cloud.githubusercontent.com/assets/14067417/19297824/5bcd4e0a-9083-11e6-97d1-7c52ad541302.png)

2. tried `grep -R 'pg-native' node_modules`
![image](https://cloud.githubusercontent.com/assets/14067417/19297844/88b0cbf4-9083-11e6-9cf8-85e0c830e832.png)

3. tried `delete pg.native;`
![image](https://cloud.githubusercontent.com/assets/14067417/19297919/17070d28-9084-11e6-8023-966e663f89b9.png)

I haven't know what is incorrect. I can only assume that the error happen in circular stringification of `json-stringify-safe`
