### ISSUE TITLE
Problem with captureException

### ISSUE THREAD

**Issue by matticus1181** [getsentry/raven-node#216]
I'm trying to add extra data on an explicit sending of an exception. The docs say that an optional param of JSON may be sent. I have:

```
var client = new raven.Client('key@sentry.io/key');
client.captureException(err.err, {
    extra: {
        request: (err.req !== undefined) ? JSON.parse(stringify(err.req)) : '',
    	response: (err.res !== undefined) ? JSON.parse(stringify(err.res)) : '',
    	inputParams: (err.input !== undefined) ? JSON.parse(stringify(err.input)) : ''
    }
});
```
But when done like this, no exception is sent to Sentry, but if I remove the extra param, it sends fine.

Any help would be appreciated. Thanks!

**Comment by LewisJEllis** [comment]
Hmm, this looks right as long as you don't have bad inputs.

Could you give me a more concrete minimal example of values of `err.err`, `err.req`, `err.res`, and `err.input` where this fails? Do you see it fail with any `extra` property at all, or only with the `request` `response`, `inputParams` properties as you have them?

Also, are you sure that none of your `JSON.parse` or `stringify` calls are throwing?

**Comment by matticus1181** [comment]
it's quite possible that something was wrong in the JSON of those properties. it didn't appear to be throwing, but when I simplified it to the following, it works. Go figure:
```
var extraParams = ''

		if (wrapper) {
			if (wrapper.req !== undefined) {
				delete wrapper.req.session.user_info.shared['email'];
				delete wrapper.req.session.user_info.shared['last_name'];
				extraParams = {
					session: wrapper.req.session,
					headers: wrapper.req.headers,
					url: wrapper.req.url,
					method: wrapper.req.method,
					originalUrl: wrapper.req.originalUrl,
					route: wrapper.req.route
				};
			}
			if (wrapper.input !== undefined) {
				extraParams.input = wrapper.input;
			}
			client.captureException(err, {
				extra: {
					data: extraParams
				}
			});
		} else {
			client.captureException(err);
		}
```

**Comment by LewisJEllis** [comment]
Yea, in that case my best guess is that something was blowing up in parsing/stringifying. Feel free to reopen if you find a reproduction that you can't explain.
