### ISSUE TITLE
uncaught exception in WebSockets

### ISSUE THREAD

**Issue by fatbattk** [getsentry/raven-node#222]
From testing both the Node and Express middleware, errors thrown in WebSockets are not behaving as expected.

On the Node test, `client.patchGlobal();` was used but gives this error,

> 27 Oct 00:22:51 - uncaughtException: 5e329a4095b747e583b44bdf068dxxxx

It however logs in Sentry.  However, that error can be _bypassed_ by explicitly calling `client.captureMessage('Error!')` manually everywhere.

Express on the other hand does not log at all and simply fails to automatically catch any thrown errors.

**Comment by LewisJEllis** [comment]
It's difficult to follow what you mean by your two different test cases without example code; could you provide a couple snippets to show what you're doing?

**Comment by fatbattk** [comment]
Here's a quick test using the Node config. Error shows on websocket connection.

```
var server = require('http').createServer()
  , WebSocketServer = require('ws').Server
  , wss = new WebSocketServer({ server: server })
  , express = require('express')
  , app = express()
  , port = 4080
  , raven = require('raven')
  , client = new raven.Client('https://xxx:yyy@sentry.io/123456');

client.patchGlobal();

wss.on('connection', function connection(ws) {
  console.log('Pre-Throw!');
  throw new Error('Error!');
  console.log('Post-Throw!');
});

server.on('request', app);
server.listen(port, function () { console.log('Listening on ' + server.address().port) });
```
Output:
```
Listening on 4080
Pre-Throw!
27 Oct 17:26:35 - uncaughtException: 881ff6c61b8f45e6a0e331926f16xxxx
```

**Comment by MaxBittker** [comment]
this is interesting, are the ws errors caught correctly if express is out of the equation?

**Comment by LewisJEllis** [comment]
Oops, @fatbattk I just saw that you gave an example snippet, sorry for the delay.

I don't think Express is relevant to this example, imported but not really used. The `<date> - uncaughtException: <eventId>` line you're seeing is just a console print that `patchGlobal` does [here](https://github.com/getsentry/raven-node/blob/ce62715c6d112ba401a14e1328e9a1647dd71c31/lib/client.js#L258). The output you provide (and which I confirmed locally) seems expected to me, and it sounds like you're seeing that error in your dashboard, so I don't think there's anything wrong in that case.

I'm not sure what you mean, though, by "Express on the other hand does not log at all". If you're using our Express middleware, the error won't go through `patchGlobal`'s global handler, so you won't see that `<date> - uncaughtException: <eventId>` console printout, but you should see the error in your dashboard. Do you have an example with Express where you expect to see an error show up in your dashboard but it doesn't?

**Comment by kamilogorek** [comment]
This issue has been closed due to close to a year of inactivity. If anyone feels that it should be reopened, please feel free to reopen it and letting me know. Thanks.
