### ISSUE TITLE
mergeContext is shallow and could be better if it went deeper

### ISSUE THREAD

**Issue by LewisJEllis** [getsentry/raven-node#228]
Right now it just throws our `extend` helper at the context object, which is a shallow non-recursive merge, so:
```javascript
Raven.setContext({
  user: {
    username: 'lewis',
  }
});
Raven.mergeContext({
  user: {
    email: 'lewis@...'
  }
});
console.log(Raven.getContext().user);
```
currently gives us:
```
{
  email: 'lewis@...'
}
```
but we might prefer/expect to get:
```
{
  username: 'lewis',
  email: 'lewis@...'
}
```
It only does mergey stuff in not clobbering any keys on the ctx other than `user`, but it's just replacing the old value of user with the new one.

Right now to accomplish this, we need to do something like:
```javascript
var currUserCtx = Raven.getContext().user;
var newUser = goDoOurOwnMerge(currUserCtx, { email: 'lewis@...' });
Raven.mergeContext({ user: newUser });
```

The context data needs to be json-serializable anyway and we use json-stringify-safe, but we should also be careful not to let merging trip on recursion/circular reference problems. I think just going one level deeper should keep this simple and still make `mergeContext` significantly more helpful, but I haven't really ruled out other options.

/cc @benvinegar @MaxBittker for thoughts

**Comment by MaxBittker** [comment]
+1 on just merging 1 (or even 2) levels deep, sounds like it's a solid improvement with few downsides.

**Comment by btipling** [comment]
Being able to nests contexts would be really nice also, perhaps that's a separate issue or feature.

**Comment by kamilogorek** [comment]
I'm not sure if we should provide such a functionality out of the box, as it's often too app specific (merge depth, removing certain keys etc.).

What if we'd either just leave `setContext/getContext` and let users merge the values however they want, or make `mergeContext` (or alias it to `changeContext`) take a function as a first argument, which'd expose current context, otherwise leaving functionality as it is (or even better, merge 1-level deep, which'd be helpful for arrays), preserving backward-comp?

```js
Raven.setContext({
  some: {
    key: 'kamil',
  },
  tags: ['foo']
});

Raven.mergeContext({
  some: {
    otherKey: 'kamil@sentry.io'
  },
  tags: ['bar', baz']
});

console.log(Raven.getContext());

// {
//   some: {
//     key: 'kamil',
//     otherKey: 'kamil@sentry.io',
//   },
//   tags: ['foo', 'bar', baz']
// }
```

```js
Raven.mergeContext((ctx) => {
  console.log(ctx); // { tags: ['foo', 'bar', baz'] }

  return Object.assign(ctx, {
    extra: 'something extra'
  });
});

console.log(Raven.getContext());

// {
//   extra: 'something extra',
//   tags: ['foo', 'bar', baz']
// }
```

cc @MaxBittker @benvinegar

**Comment by btipling** [comment]
I like the idea of a function as a first argument. That would really help.

**Comment by MaxBittker** [comment]
I think this could be a good, reasonable solution, except that it's not necessarily better than what you can already do manually with setContext, right?

**Comment by benvinegar** [comment]
This is still relatively low priority.

**Comment by kamilogorek** [comment]
@MaxBittker yes, that's why my first proposed solution would be to just stick to the `setContext/getContext` exclusively and/or even deprecate `mergeContext` to make the API smaller.

**Comment by kamilogorek** [comment]
Closing this one, as I believe we can achieve everything using set/get context and it's low priority
