### ISSUE TITLE
Implications of making the secret key available to the client (electron)

### ISSUE THREAD

**Issue by MrBlenny** [getsentry/raven-node#232]
When using raven-node in an electron application - the private DSN (containing the secret key) will inevitably become accessible by the client (as they are running the electron/node application on their computer.

* What are the implications of this?
* Is this a major security hole?
* Is it possible to use rave-node with just the public DSN?

**Comment by mattrobenolt** [comment]
This comes up often, and it's not a security issue. The worst that could happen is someone could use this DSN and report events into your project. This is effectively the same risk as any API key for any other service.

And to be super clear: no bits of this DSN provide access to anything outside of event ingestion. It's not possible to use anything from the DSN to query the API or do any other mutations.
