### ISSUE TITLE
Error in raven.lib:client

### ISSUE THREAD

**Issue by sabrehagen** [getsentry/raven-node#234]
Hi,

We're getting an error inside the raven client library v0.12.1 on node v7.0.0. Here's the issue: http://35.162.145.41:9000/share/issue/332e3234/

Jackson

**Comment by LewisJEllis** [comment]
It looks like this is just due to bluebird passing us an "error" that isn't an `Error` object. We create an `Error` instance in order to report a stack trace, but it's not actually a problem in raven-node - we're just catching the error that happened elsewhere and wrapping it to get more info.
