### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by pbadenski** [getsentry/raven-node#241]
This happens when using [handsontable](https://github.com/handsontable/handsontable) library. When typing anything into a cell on each keystroke an exception gets thrown:

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at before (raven.js:886)
    at wrapped (raven.js:270)
```

Raven version used: 3.9.0
Handsontable version used: "0.29.0"

**Comment by LewisJEllis** [comment]
Looks like this is happening [here](https://github.com/getsentry/raven-js/blob/master/src/raven.js#L886) in raven-js; did you meant to open this [here](https://github.com/getsentry/raven-js/issues/new)?

**Comment by pbadenski** [comment]
Yes. Sorry, even after double checking I posted in a wrong repo ;]
