### ISSUE TITLE
Documentation Out of Date for 1.0.*

### ISSUE THREAD

**Issue by joshdickson40** [getsentry/raven-node#247]
I'm trying to figure out what's going on here so I can bump the installed version of this to the new 1.0.* major (which, congrats on releasing, by the way).

In the change log I see:

`Raven.config(...) instead of new raven.Client(...)`
`Raven.install() instead of client.patchGlobal()`

However it doesn't look like [the documentation](https://docs.sentry.io/clients/node/) reflects these changes yet. Maybe we can get a better idea what the new usage is supposed to be for this?

Thanks!

**Comment by LewisJEllis** [comment]
I'm still finishing the complete docs (glad you noticed, sorry for the delay!), but most of the new usage is covered in the [forum post](https://forum.sentry.io/t/node-js-client-1-0-0-and-1-1-0-release/641) where we announced it and the prior [1.0.0-beta post](https://forum.sentry.io/t/node-js-client-1-0-0-and-1-1-0-release/641).

I'll keep this open until those docs are updated (likely later today).

**Comment by joshdickson40** [comment]
Ah, I didn't even know you guys had a forum but that looks like a better description of what I'm looking for. Thanks Lewis!

**Comment by LewisJEllis** [comment]
Docs have been updated [here](https://docs.sentry.io/clients/node/) - have a look and please feel free to open issues related to typos, thinly-covered sections, possible clarifications, etc!

**Comment by imbstack** [comment]
@LewisJEllis I'm still seeing the old documentation at the link you provided. Is it possible it has reverted back for some reason?

**Comment by LewisJEllis** [comment]
Hmm, sure enough, I'm seeing the old docs now too - that's really strange. I'll investigate.

**Comment by LewisJEllis** [comment]
@imbstack it looks like the repo where we combine all our different raven-<language> docs somehow got a couple of its submodules kicked back to November in a recent change, so raven-node and raven-python docs were a few months out of date. Fixed - thanks for reporting.

**Comment by imbstack** [comment]
Thanks very much for the quick fix!
