### ISSUE TITLE
Auto breadcrumbs HTTP causes DynamoDB errors in AWS Lambda environments

### ISSUE THREAD

**Issue by adambiggs** [getsentry/raven-node#248]
I tried using `autoBreadcrumbs: true` in an AWS Lambda function, but when deployed to AWS all my DynamoDB operations started failing with `Error: CRC32CheckFailed: CRC32 integrity check failed` errors.

The errors went away after changing my Raven config to `autoBreadcrumbs: { console: true }`.

**Comment by LewisJEllis** [comment]
Interesting, thanks for the report. I'm not familiar with DynamoDB, but I'm assuming operations with it are done via HTTP? Is the DynamoDB interface you're using from some npm package I can investigate, or is it through Lambda's APIs?

**Comment by adambiggs** [comment]
The error is thrown by the `aws-sdk` v2.7.10 NPM module.

**Comment by rpm0618** [comment]
I just want to add that I've also been experiencing issues with HTTP breadcrumbs and other AWS services. In particular, with Simple Notification Service (SNS), I've been getting empty responses when I try to create an endpoint or subscribe to a topic. Turning http breadcrumbs off resolves the issue.

My Environment:
- node 6.0.0
- raven 1.1.1
- express 4.13.4 (I'm using the raven middleware)
- aws-sdk 2.3.11

I've had this happen on both Windows 10 and Ubuntu 14.04. If there is any more info you would like let me know!

**Comment by nicka** [comment]
We're having the same issues on S3 calls where the result becomes empty! 😢

**Comment by ceylanismail** [comment]
> We're having the same issues on S3 calls where the result becomes empty! 😢

Yes we too! So weird, `autoBreadcrumbs: true` mysteriously eats all the Buffer data 😄 Here is the code, and outputs:

Sample S3 GetObject call:

```
getObject: function (key, raven) {
    return new Promise(function (resolve, reject) {
        s3.getObject({
            Bucket: S3_BUCKET,
            Key: key
        }, function (err, data) {
            console.log(data);
            return err ? reject(err) : resolve(data);
        });
    });
}
```

Output:

```
when autoBreadcrumbs: true

{ AcceptRanges: 'bytes',
  LastModified: 'Thu, 10 Dec 2015 13:01:32 GMT',
  ContentLength: '77037',
  ETag: '"<masked>"',
  VersionId: '<masked>',
  ContentType: 'image/png',
  Metadata: {},
  Body: <Buffer > }
```

```
when autoBreadcrumbs is not defined

{ AcceptRanges: 'bytes',
  LastModified: 'Thu, 10 Dec 2015 13:01:32 GMT',
  ContentLength: '77037',
  ETag: '"<masked>"',
  VersionId: '<masked>',
  ContentType: 'image/png',
  Metadata: {},
  Body: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 01 9e 00 00 03 35 08 06 00 00 00 40 38 97 0b 00 00 00 01 73 52 47 42 00 ae ce 1c e9 00 00 40 00 ... > }
```

I'll add more findings, if I can do more digging to the issue.

raven version: v1.1.1
node version: v6.2.0
aws-sdk: v2.7.0

**Comment by alexcroox** [comment]
Seeing this behaviour with AWS SQS, the messages are coming through as empty when Raven is installed

**Comment by LewisJEllis** [comment]
Thanks for all the reports! A few clarifying questions for all of you so I can better understand where this is occurring; some have already answered one or more of these but I'd like to know what all cases exist.

- Which of these are in Lambda projects vs standard node project but just using aws-sdk?
- Are you using native promises anywhere in your application code? (i.e. `new Promise` etc without bluebird or similar)
- When you disable autoBreadcrumbs and things start working again, are you still using a `Raven.context()` and/or the `Raven.requestHandler()` express middleware?

**Comment by adambiggs** [comment]
@LewisJEllis 

- Yes, this is in Lambda.
- Yes, we're using native promises
- No, we're not using `Raven.context()` or `Raven.wrap()`. Raven is using the global context.
