### ISSUE TITLE
Getting CORS error

### ISSUE THREAD

**Issue by danny-larsen** [getsentry/raven-node#258]
I get the following error. The project is a react js project, so it is running in the browser and compiled with webpack.

Response to preflight request doesn't pass access control check: Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials. Origin 'MYDOMAIN' is therefore not allowed access.

**Comment by benvinegar** [comment]
@danny-larsen – this is raven-node, Sentry's Node client library. Did you mean to open this on [raven-js](https://github.com/getsentry/raven-js), our browser client?

**Comment by danny-larsen** [comment]
But i use the node client in my dev environment and it then gets compiled to javascript i guess. I want to be able to send custom errors from my javascript React code, but then I need to import the raven client, right?

**Comment by LewisJEllis** [comment]
You'll definitely need to be using our browser JS client, raven-js. I'm not even sure how you got raven-node to run in that case, since it depends on node core libraries. Are you using the `raven` package from npm, or `raven-js`?

**Comment by danny-larsen** [comment]
I think I tried the raven. Because I tried using the "<script src="https://cdn.ravenjs.com/3.9.1/raven.min.js"></script>" in the html, but then I cannot call "Raven.captureException" from my React code, because I have to import "Raven" from somewhere?

**Comment by LewisJEllis** [comment]
If you're including raven.min.js from the cdn, that's the browser client. I'd take a look at our [browser js docs](https://docs.sentry.io/clients/javascript/) and specifically the [react section](https://docs.sentry.io/clients/javascript/integrations/react/) to make sure you've set it up correctly. If you still have a CORS problem after that, I'd recommend opening an issue on the [raven-js repo](https://github.com/getsentry/raven-js).

**Comment by danny-larsen** [comment]
This was related to the JS client. Managed to get it working, but thanks for the assistance.
