### ISSUE TITLE
bread crumbs for pg does not work

### ISSUE THREAD

**Issue by gbartlett9089** [getsentry/raven-node#263]
It looks like breadcrumbs for node-pg is not working properly.  The default bread crumbs looks like this:

`var autoBreadcrumbDefaults = { console: false, http: false,  pg: false };`

However, when `instrument` is called, `wrappers['pg'](Raven)` returns `undefined`.

The correct key would be `wrappers['postgres'](Raven)`.  However, because there is no **postgres** key in `autoBreadcrumbDefaults`, `options.autoBreadcrumbs.postgres` is never set even if `postgres: true` is passed in the Raven config object.

I'm using 1.1.1

**Comment by LewisJEllis** [comment]
Thanks for the report - was probably a mixup when I did some refactoring of the instrumentation logic. Fix in #270.

**Comment by gbartlett9089** [comment]
Looking at the source code I figured it was pretty simple fix.  Thanks for this!
