### ISSUE TITLE
release not being sent with exceptions

### ISSUE THREAD

**Issue by hamiltondanielb** [getsentry/raven-node#275]
raven version: 1.1.2
node version 6.4.0

I am trying to set up node side logging, the unhandled exceptions work find and I see them inside sentry. However, I do not see the release value (it is null) on the json sent to sentry 
```
{
id: "317081be2f594df19bb78771b3a9fcf6",
project: 108,
release: null,
platform: "node",
culprit: "middleware:runtimeError at RuntimeError",
message: "Error: RuntimeError middleware",
datetime: "2017-02-22T22:27:59.000000Z",
time_spent: null,
...
````

I setup the client via 
```
const client = new raven.Client(process.env.SENTRY_DSN, {release: process.env.UACF_BUILD_ID})
```
I know both env vars are set (i use the same values for raven-js side and i get the build id).

I am also adding 
`  app.use(raven.middleware.express.requestHandler(process.env.SENTRY_DSN));` at the top. Am I missing anything else from the setup?

**Comment by LewisJEllis** [comment]
Your setup should look more like:
```javascript
raven.config(process.env.SENTRY_DSN, { release: process.env.UACF_BUILD_ID }).install();
...
app.use(raven.requestHandler());
```

The `raven.middleware.express...` and `new raven.Client` patterns are from older 0.x versions just kept around for BC purposes. Your current setup is non-obviously resulting in two separate client instances (one for the middleware and one with your release config); this was a point of confusion that we wanted to get away from, hence new usage patterns. Take a look at the [express docs](https://docs.sentry.io/clients/node/integrations/express/) for a quick rundown on the new recommended usage patterns.
