### ISSUE TITLE
What is fingerprinting?

### ISSUE THREAD

**Issue by cbrunnkvist** [getsentry/raven-node#279]
As documented on https://docs.sentry.io/clients/node/usage/

> fingerprint
> The fingerprint for grouping this event.
> 
> {
>     // dont group events from the same NODE_ENV together
>     fingerprint: ['{{ default }}', process.env.NODE_ENV]
> }
> 

I have no idea what this means. It feels like the first sentence and the comment contradict each other.

Can we update the docs with a slightly less terse description? :)

Thanks

**Comment by benvinegar** [comment]
Docs here: https://docs.sentry.io/learn/rollups/.

**Comment by benvinegar** [comment]
That page is [now linked from docs](https://github.com/getsentry/raven-node/commit/bff4e3be820ce4f86cc356ec316823d91574f564) – thanks.

**Comment by mshwery** [comment]
>// dont group events from the same NODE_ENV together

I agree – this line sounds contradictory. Is it accurate? Should it be:
>// group events from the same NODE_ENV together

or
>// dont group events from different NODE_ENVs together
