### ISSUE TITLE
Raven node client may happen memory leak

### ISSUE THREAD

**Issue by gzhappysky** [getsentry/raven-node#286]
if you enable breadcrumb.but do not set node domain.when you use Raven.breadcrumb to record that it set breadcrumb info to _globalContext.but _globalContext always do not clear.until application close.

**Comment by LewisJEllis** [comment]
Unless I'm missing something, this does not actually leak memory. You're correct that the global context is not cleared at any point, but it also doesn't grow beyond a certain limit.

We have a `maxBreadcrumbs` option which defaults to 30 and cannot be set higher than 100; if the context's breadcrumbs array is longer, then next time a breadcrumb is captured we remove one [here](https://github.com/getsentry/raven-node/blob/770c8e6e5e3b48a0e114fb67ce5a6e78d9b97a1b/lib/client.js#L434). I don't think it matters whether we're using global context or not; we'll never store more than `maxBreadcrumbs` breadcrumbs in one context.

Closing, but please reopen if you can demonstrate a repro.
