### ISSUE TITLE
How to implement sentry using restify npm 

### ISSUE THREAD

**Issue by dibeesh** [getsentry/raven-node#287]
I have implented sentry using express npm successfully.
Currently I am trying to implement the sentry using restify in my another app.
But I could not getting any "uncaughtException".
How to implement sentry using restify npm?

**Comment by LewisJEllis** [comment]
We don't have a middleware for restify yet. For now I would recommend taking a look at restify's error handling docs and adding hooks to some of its mechanisms to call `Raven.captureException`. Specifically for `uncaughtException`, restify server objects will emit an `uncaughtException` event that you might want to listen for.
