### ISSUE TITLE
How can I log uncaught exceptions to the console while also using raven-node?

### ISSUE THREAD

**Issue by ClaasM** [getsentry/raven-node#293]
Consider the following snippet:

`var Raven = require('raven');
Raven.config('https://abc@sentry.io/123').install();
throw new Error();`

The thrown error is not printed to console.error; instead, `raven@1.1.2 alert: uncaughtException: abc123` is logged.

During development, I (obviously) still need to _see_ uncaught Exceptions for debugging.

I assume I misunderstood something, can someone point me in the right direction?
Thanks!

**Comment by LewisJEllis** [comment]
Along the lines of #288, this is a current shortcoming being addressed as part of work for #257. I didn't initially give enough consideration to what ideal behavior would be in the "development before production" use case.

For a workaround for now, you could listen to the `logged` event:
```javascript
Raven.on('logged', function (err) {
  console.log('raven reported an error:');
  console.error(err);
});
```
or use the (currently undocumented) `install` callback:
```javascript
Raven.config(...).install(function (sent, err) {
  console.log('error caught by raven:');
  console.error(err);
});
```
These do roughly the same thing.
