### ISSUE TITLE
Be able to select log level

### ISSUE THREAD

**Issue by Almad** [getsentry/raven-node#3]

**Comment by bgSosh** [comment]
So, what's the proper way to pass this level param at log time?  

I've tried @kof  's method: 

client.captureMessage('Message', {level: 'info'});

But that doesn't seem to work - the message gets logged at the default 'error' level.   And in the sentry interface there is this error:

There was 1 error encountered while processing this event.
Discarded invalid value for parameter 'level' Collapse
{
  "name": "level",
  "value": "warn"
}
