### ISSUE TITLE
Can't get Raven to work with express

### ISSUE THREAD

**Issue by farhansalam** [getsentry/raven-node#306]
I am testing with a simple express app

```javascript
import express from 'express';
import cors from 'cors';
import Raven from './raven';
import config from './configs';

Raven.config(config.sentry.DSN, {
  captureUnhandledRejections: true
}).install();
Raven.on('logged', function () {
  console.log('raven event sent');
});

const app = express();
app.use(Raven.requestHandler());
app.use(Raven.errorHandler());
app.use(cors());
// health check
app.get(`/health`, (req, res) => {
  throw new Error('get request fail');
  res.sendStatus(200);
});

export default {
  start: () => {
    app.listen(5050, () => {
      console.log('Listening on 5050');
    });
  },
};

```
Hitting the url with `curl` throws error in the console but error is not sent to Sentry and also the `error` event never gets called.

**Comment by farhansalam** [comment]
nevermind found a solution here https://github.com/getsentry/raven-node/issues/24#issuecomment-60571496 

You can have to use raven `middleware` after the `paths`

```javascript
...
app.use(cors());
// health check
app.get(`/health`, (req, res) => {
  throw new Error('get request fail');
  res.sendStatus(200);
});
app.use(Raven.requestHandler());
app.use(Raven.errorHandler());
...
```

[Reference](https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x)

**Comment by LewisJEllis** [comment]
You need to use the `requestHandler` middleware *before* your other paths/middlewares and the `errorHandler` middleware *after*. This is documented [here](https://docs.sentry.io/clients/node/integrations/express/).
