### ISSUE TITLE
setTagsContext not defined

### ISSUE THREAD

**Issue by DanielMSchmidt** [getsentry/raven-node#326]
In the History.md file it is written that setTagsContext is supported, but it isn't. Can it be readded to this project? Would be great to be nearer to the official documentation 👍

**Comment by LewisJEllis** [comment]
I'm not sure where you're seeing that it's supported. From release notes/history.md on version 2.0.0:
> Removed various deprecated methods [See #313]

Also, `setTagsContext` is a deprecated no-op for all of v1.x, and using it on any 1.x version will print the following alert:
> setTagsContext has been deprecated and will be removed in v2.0; use setContext instead
