### ISSUE TITLE
raven@2.0.2 alert: failed to send exception to sentry: HTTP Error (413): undefined

### ISSUE THREAD

**Issue by steveherschleb** [getsentry/raven-node#327]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Has someone had this problem before?**

Some issues seem related, but I'm not sure if they are the same or not.

**What is the current behavior?**
I attempted to add Sentry to my existing project, following the example here: https://docs.sentry.io/clients/node/integrations/express/

Unfortunately when I hit my test route to get the exception to throw, I get this message in my console: 

```
raven@2.0.2 alert: failed to send exception to sentry: HTTP Error (413): undefined
```

I tried to creating a "dummy" that uses just the code in the docs example, and it worked fine. Of course the 413 code is for too large of a payload, so perhaps because my existing project is fairly extensive, it's trying to send too much code or data? 

I'm on node v8.0.0 and npm v5.0.0. 

**What is the expected behavior?**
To send the exception report!

**Comment by hmilkovi** [comment]
+1 same issue with 301 http error permanent moved

**Comment by gleuch** [comment]
Enabling breadcrumbs with the default limit of 30 included so much data that the large payloads that were sent are being rejected by Sentry's servers. 

We reduce breadcrumbs tracking limits from default (30) to 10 so we can continue tracking errors. Perhaps Sentry team can increase payload size limit on their servers.

**Comment by hmilkovi** [comment]
I fixed my issue documentation for Express v4 and Raven v2.x.x is a bit lacking.

**First before any routes:**
raven.config(SENTRY_DSN).install();
**then after routes:**
app.use(raven.errorHandler());

**Comment by nullpixel** [comment]
Same issue here.

**Comment by steveherschleb** [comment]
I updated to the latest and greatest verion of `raven-node`, and it all seems to be working for me. Checking the history file, it looks like the 2.1.0 likely resolved this: https://github.com/getsentry/raven-node/blob/master/History.md#210---6202017
