### ISSUE TITLE
Breadcrumbs in Raven

### ISSUE THREAD

**Issue by prasantarmaye** [getsentry/raven-node#331]
Hi,

I am using Raven in my openERP project to log to Sentry. During this, I have observed that the breadcrumbs limit cannot be set by the client through the API. I can only enable_breadcrumbs or disable them. I would like to log breadcrumbs for ERROR only.

To summarise, I am looking forward to:
1. Set the limit for number of breadcrumbs from client.
2. To log breadcrumbs for specific log levels.

Below is additional information:
I have gone through the Raven package and understood that we are getting breadcrumbs if below statement is true-
# insert breadcrumbs
if self.enable_breadcrumbs:

Also breadcrumbs limit is set to 100, in breadcrumbs.py that can't be changed by client.

Please let me know if we have a workflow to get these items through the API else, can these changes be provided in your upcoming releases.

Thanks,
Prasantarmaye

**Comment by LewisJEllis** [comment]
This is the repository for the Node.js SDK; it sounds like you're looking for https://github.com/getsentry/raven-python.
