### ISSUE TITLE
Sentry keeps catching unhandled promise rejections even when disabled

### ISSUE THREAD

**Issue by SeMeKh** [getsentry/raven-node#336]
Configuring raven with `Raven.config('', { captureUnhandledRejections: true }).install()` outputs:
```
raven@2.1.0 alert: no DSN provided, error reporting disabled
```
so I expect my code to behave as if raven wasn't there. But having an unhandled promise rejection in your code will result in the following line:
```
raven@2.1.0 alert: unhandledRejection captured: 4fd6ed2f1b5645b3bc143ca6c343edeb
```
which differs from node's behavior when raven is actually disabled: (i.e. not `.config`ed)
```
(node:3653) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
```
This becomes a bit annoying for a developer since he/she doesn't have any clue about what had caused the unhandled promise rejection.

**Comment by MaxBittker** [comment]
hi @SeMeKh - I see how this is confusing, it's possible that we should special case what gets printed when no DSN is provided. could you help me understand why you're disabling sentry by passing a null dsn instead of just not installing it?

**Comment by kamilogorek** [comment]
Ping @SeMeKh

**Comment by SeMeKh** [comment]
I had totally forgotten about this. Thanks for the ping. :)

Are you suggesting that I should put a condition around every raven-related code? or just skipping the install call should work?

**Comment by kamilogorek** [comment]
No, we're just curious why would you ever call `config` without providing a valid DSN?

**Comment by SeMeKh** [comment]
Because I read the DSN from env variables, and most developers don't provide it during their development, and I assumed it was alright because of the warning `raven@2.1.0 alert: no DSN provided, error reporting disabled`.

**Comment by kamilogorek** [comment]
Oh, this way. Reporting is indeed disabled (as in - it won't send any requests), but it will still perform instrumentation and catching of the errors.

The easiest solution for this is to just check whether env variable is available before calling Raven's config method.

**Comment by SeMeKh** [comment]
Doesn't this break other raven calls in anyway? Like, is it okay to skip the config step, but still keep the raven express middleware in place?

**Comment by kamilogorek** [comment]
It won't attach any listeners, collect breadcrumbs and it will silently bailout during error processing.

https://github.com/getsentry/raven-node/blob/6dc8bc1d80ef736ee813bb76574a2a449d19cc85/lib/client.js#L270

https://github.com/getsentry/raven-node/blob/6dc8bc1d80ef736ee813bb76574a2a449d19cc85/lib/client.js#L81-L82

**Comment by kamilogorek** [comment]
Closed due to inactivity. Please feel free to reopen if it's still relevant.
Cheers!
