### ISSUE TITLE
How to capture send to sentry error when using errorHandler?

### ISSUE THREAD

**Issue by wong2** [getsentry/raven-node#337]
I know if I capture errors mannuly with `captureException`, I can know if the error fails to send to sentry in the callback:

```
Raven.captureException(err, function (sendErr, eventId) {
  // check sendErr
})
```

but what if I'm using `Raven.errorHandler()` in express? I can't find a way to do this in the document

**Comment by kamilogorek** [comment]
Unfortunately there's no way to do this right now https://github.com/getsentry/raven-node/blob/master/lib/client.js#L484-L496.

Feel free to send a PR if you think this is something that'd be helpful to you.

**Comment by benvinegar** [comment]
A possible implementation could be to pass the callback function through `Raven.errorHandler`.

```javascript
Raven.errorHandler(function (sendErr, eventId) {
  // check sendErr
});
```
