### ISSUE TITLE
Mongoose support (automatically calls `req.user.toObject()` for us)

### ISSUE THREAD

**Issue by niftylettuce** [getsentry/raven-node#347]
Right now if you're using Mongoose and you set `req.user = User.findById(...)` then it will be a Mongoose object that needs transformed before running against `parseUser` function.  Otherwise the object cannot be parsed until it is transformed with `req.user.toObject()`.

I suggest a small rewrite of the default `parseUser` implementation:

```js
  if (parseUser) {
    var user = {};
    if (typeof parseUser === 'function') {
      user = parseUser(req);
    } else if (req.user) {
      var _user = req.user;
      // adds support to automatically convert mongoose objects
      if (_user.toObject) _user = _user.toObject();
      if (parseUser === true) {
        for (var key in _user) {
          if ({}.hasOwnProperty.call(_user, key)) {
            user[key] = _user[key];
          }
        }
      } else {
        parseUser.forEach(function (fieldName) {
          if ({}.hasOwnProperty.call(_user, fieldName)) {
            user[fieldName] = _user[fieldName];
          }
        });
      }
    }

    // client ip:
    //   node: req.connection.remoteAddress
    //   express, koa: req.ip
    var ip = req.ip || req.connection && req.connection.remoteAddress;
    if (ip) {
      user.ip_address = ip;
    }

    kwargs.user = user;
  }
```

**Comment by benvinegar** [comment]
Is there any reason why Mongoose users can't use `parseUser` like so?

```javascript
Raven.config('your-dsn', {
  parseUser: function (user) {
    return user.toObject();
}).install();
```

I do agree that we shouldn't choke on `user` if it isn't a proper JavaScript object. But I'm not sure we should be writing Mongoose-specific code.

**Comment by niftylettuce** [comment]
Mongoose is so widely used and popular I feel like it should be built in by default - just like support for Express / Connect exists.  However we should at least document it regarding Mongoose.  Also `.toObject()` might not be for everyone - I know some folks have `req.user` as a plain object, and others have it as a Mongoose object so they can easily make changes, e.g. `req.user.name 'Foo';` and then `await req.user.save();`.

**Comment by niftylettuce** [comment]
See <https://github.com/getsentry/raven-node/issues/359#issuecomment-320502627>

**Comment by benvinegar** [comment]
Re-opening. At the very least, we should avoid sending `[object Object]`.
