### ISSUE TITLE
Name of error class retrieved in the wrong way

### ISSUE THREAD

**Issue by deefeloper** [getsentry/raven-node#350]
Currently, sentry always shows `Error` as the name of the error because in parser,js it says:

`var name = err.name + '';`

https://github.com/getsentry/raven-node/blob/master/lib/parsers.js#L18

This should be changed to:
`var name = err.constructor.name;`

So that when you create custom errors which extend `Error` it will use the correct name

**Comment by benvinegar** [comment]
Makes sense. +1.
