### ISSUE TITLE
Provide a way to set the DSN before sending a message

### ISSUE THREAD

**Issue by bradfordh** [getsentry/raven-node#351]
Currently, `raven-node` does not provide a way to set the DSN before a message is sent. This type of functionality is exposed in `raven-js` via [`setDSN()`](https://github.com/getsentry/raven-js/blob/9fec3271ece1db5a8cdb5adbf6f5ebc6628dc55b/src/raven.js#L220-L239), and it can be useful in situations where more than one DSN is tied to a single deployment. Two possible options for implementing this are (i) exposing a similar setDSN() method as `raven-js` does or (ii) adding something like a dsnCallback option that is invoked before messages are sent.

Is there any interest in this functionality? Thanks for your time!

**Comment by LewisJEllis** [comment]
I'm not sure what you mean here. If you want to send to multiple DSNs, you can have multiple instances ([note in docs](https://docs.sentry.io/clients/node/usage/#multiple-instances)):
```js
var Raven = require('raven');
var Raven1 = new Raven.Client(dsn1);
var Raven2 = new Raven.Client(dsn2);
Raven1.captureException(new Error('goes to dsn 1'))
Raven2.captureException(new Error('goes to dsn 2'))
```

**Comment by bradfordh** [comment]
@LewisJEllis Good point. More context is probably needed here. Right now, if you want to send an error to either `dsn1` or `dsn2` in an Express app, then you can to do something like the following:

```js
const app = require('express')()
const Raven = require('raven')

const Raven1 = new Raven.Client(dsn1, {
    shouldSendCallback: (data) => {
        // should send?
    }
})
const Raven2 = new Raven.Client(dsn2, {
    shouldSendCallback: (data) => {
        // should send?
    })

app.use(Raven1.requestHandler())
app.use(Raven2.requestHandler())

app.get('/', (req, res) => {
    throw new Error('goes to dsn x')
})

app.use(Raven1.errorHandler())
app.use(Raven2.errorHandler())

app.listen(3000)
```

The only drawbacks to this approach are that you need to instantiate multiple clients and if the shouldSendCallback() methods get out of sync and all return false then you might not be capturing the error at all. The idea mentioned in the first post is a nice-to-have in this situation so that you only have to instantiate one client and you could always have a default DSN applied, avoiding the case where both shouldSendCallback() methods return false. For example, 

```js
const app = require('express')()
const Raven = require('raven')

Raven.Config(dsn, {
    setDsnCallback: (data) => {
        if (/* condition 1 */) {
            return dsn1
        }
        
        if (/* condition 2 */) {
            return dsn2
        }

        return defaultDsn
    }
})

app.use(Raven.requestHandler())

app.get('/', (req, res) => {
    throw new Error('goes to dsn x')
})

app.use(Raven.errorHandler())

app.listen(3000)
```
