### ISSUE TITLE
Fix HTTP breadcrumb instrumentation tests for Node 8

### ISSUE THREAD

**Issue by benvinegar** [getsentry/raven-node#352]
As part of CI, on top of raven-node's _regular_ test suite, we also run the full Node.js core http test suite w/ our HTTP breadcrumb instrumentation to verify that we don't break anything ([code here](https://github.com/getsentry/raven-node/tree/master/test/instrumentation), thanks @LewisJEllis).

Welp, seems that with Node 8 we do [fail 3 tests](https://travis-ci.org/getsentry/raven-node/jobs/258344083):

```
X test-http-outgoing-internal-headers.js - error!
X test-http-outgoing-renderHeaders.js - error!
X test-http-pipeline-flood.js - error!
```

I haven't investigated very deeply yet; opening this issue for now.

**Comment by LewisJEllis** [comment]
Note that we have some "known failures" that we've decided not to worry about [here](https://github.com/getsentry/raven-node/blob/master/test/instrumentation/http.test.js#L41), pipeline-flood being one of them, so the concern here is moreso just with the first two you listed. I wouldn't be surprised if the two new ones here are similar cases, but you'd have to dig into what those tests actually do to be sure.

Also, these failures were only introduced in Node 8.2; they were passing on 8.1.

**Comment by kamilogorek** [comment]
Fixed
