### ISSUE TITLE
Major Bug with Raven Data Sent vs. Sentry Data Report

### ISSUE THREAD

**Issue by niftylettuce** [getsentry/raven-node#359]
The data sent from `raven-node` conflicts with what the Sentry.io dashboard shows...

This is absolutely absurd - or there is a bug here with this project or my usage somewhere...

I went into `node_modules/raven/lib/client.js` and added a `console.log('send', kwargs);` inside the `send` function.

Here was the output:

```log
send { request:
   { method: 'GET',
     query_string: { page: 1, limit: 10 },
     headers:
      { host: 'localhost:3000',
        connection: 'keep-alive',
        'cache-control': 'max-age=0',
        'upgrade-insecure-requests': '1',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        dnt: '1',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.8',
        cookie: '...' },
     cookies: { ... },
     data: '{}',
     url: 'http://localhost/page/beep/boop/baz/' },
  user:
   { id: '********',
     email: 'niftylettuce@gmail.com',
     username: 'Foo Bar',
     ip_address: '::1' },
  timestamp: '2017-08-06T11:48:39',
  server_name: 'localhost',
  environment: 'development',
  level: 'warning',
  extra: {},
  message: '404 page not found',
  tags: {},
  breadcrumbs: { values: [] },
  modules: { ... },
  logger: 'winston-raven-sentry',
  event_id: '715063a4d4f444308566a413c1125317',
  project: '*****',
  platform: 'node' }
```

Now here's what's showing on the dashboard:

<img width="1157" alt="report" src="https://user-images.githubusercontent.com/523141/29003017-0678fa82-7a7d-11e7-84bc-f58b14e0040d.png">

I took a close look, and even though I clicked on the LATEST event, it won't show my development environment issue - and the event ID does not match in this screenshot above.  It's like the UI on Sentry.io is completely broken and janky... This is horrible...

Time to switch to Bugsnag?!

What's wrong here... @benvinegar @LewisJEllis?

Why am I the only one experiencing this?  Do you not have people actually using this properly?

**Comment by niftylettuce** [comment]
Closing this issue, switching to Bugsnag! cc @wordofchristian @eanakashima 🎉

**Comment by benvinegar** [comment]
> I took a close look, and even though I clicked on the LATEST event, it won't show my development environment issue - and the event ID does not match in this screenshot above.

You have 2.2k events grouped in that issue, and it appears (from the issue graph you've chosen to blur out) that you've been processing many of these events every hour over the past 24 hours. I don't think it's a given that an event you've manually transmitted is guaranteed to be the latest event when this event seems to be triggering multiple times every hour.

If you're willing to reach out to support, we can look at production data and help locate the event. But it appears that – from the comment you've made above and that you appear to have closed every issue you've ever opened – that you've decided to move on. Best of luck.
