### ISSUE TITLE
Dropping support for Node < 4.0

### ISSUE THREAD

**Issue by kamilogorek** [getsentry/raven-node#365]
Node 0.8 and 0.10 are long time deprecated now, and they require some workarounds for Raven to work, as well for tests to run.

Node 4.0 is still supported for 7 more months, so we should definitely leave it in place for now – https://github.com/nodejs/LTS

Do we have any statistics regarding Node 0.8/0.10 usage @benvinegar? Any thoughts on this?

**Comment by benvinegar** [comment]
It's okay if we move forward and drop support for 0.8 and 0.10. They can always pin to a previous version.

But we should probably add a note to the README commenting that we only support versions according to the LTS schedule.

**Comment by kamilogorek** [comment]
Started initial PR. I'm not sure whether we should wait for major release with this or not.
Do we have any usage stats of Node pre v4?

**Comment by kamilogorek** [comment]
Merged https://github.com/getsentry/raven-node/pull/368

**Comment by mitjap** [comment]
This change should definitely bump major version as it is breaking (maybe just for some users but still).
