### ISSUE TITLE
Document overriding server_name with config/ENV

### ISSUE THREAD

**Issue by francisdb** [getsentry/raven-node#373]
We are running our apps in docker and the server_name that is picked up is just a unique id for the docker container. It would be great if we could customize that field.

This has been available in raven-js for a while by setting `serverName`
https://github.com/getsentry/raven-js/pull/404

**Comment by kamilogorek** [comment]
@francisdb you can already do this, by setting `name` attribute during `config` phase or `SENTRY_NAME` env variable.

https://github.com/getsentry/raven-node/blob/98353fab8f808eaee448f89a90f25a7721434901/lib/client.js#L52
https://github.com/getsentry/raven-node/blob/98353fab8f808eaee448f89a90f25a7721434901/lib/client.js#L247

**Comment by francisdb** [comment]
Docs could be better on this, at least mentions `server_name` like it is visible in the sentry ui. The docs currently mention `SENTRY_NAME` and point to some non-existing python documentation link
https://docs.sentry.io/clients/node/config/

**Comment by kamilogorek** [comment]
Updated the issue. Thanks for pointing that out.

**Comment by kamilogorek** [comment]
Addressed in https://github.com/getsentry/raven-node/pull/377
