### ISSUE TITLE
New dependency on Python

### ISSUE THREAD

**Issue by adamdunkley** [getsentry/raven-node#385]
Recently a dependency on `memwatch-next` has been added (and then moved from dev-dependencies to dependencies). This package in turn depends on `node-gyp` and Python. We don't have Python installed as we're trying to keep our Docker image that we run node on as lean as possible. 

As a structural point I don't think it's great to put in monitoring for everyone to solve any memory problems this library might have. Probably best to put it as `optionalPeerDependencies` and to use introspection as to whether it's installed as to whether to use it? (something like on-demand require statements or the like).

At the moment we have rolled back to 1.2.0 and will have to remain on the version until the dependency is dropped.

Happy to help by contributing code to remove the dependency, if you guys agree with my suggested strategy?

**Comment by kamilogorek** [comment]
@adamdunkley it was completely unintentional mistake of mine. I totally forgot that npm, starting v5 automatically adds installed dependencies to the `package.json` and I forgot to double-check it when running my tests locally.

Released a patch in `2.2.1` which remove it from dependency list.

Thanks for pointing that out and sorry for inconvenience :)
