### ISSUE TITLE
Integrate with the 'http' library

### ISSUE THREAD

**Issue by arasmussen** [getsentry/raven-node#389]
There are a bunch of great integrations for those using libraries like Express, etc. We don't use a server framework, just an 'http' server.

It'd be great to have an integration with sentry so that we can easily add context like:
– What is the path of the request?
– What are the query params of the request?
– What is the host header?
– What are the cookies?
– Who is the logged in user?

Of course, I can pass all this in manually, just seems like a lot of work compared to something like:

```es6
http.createServer((request, response) => {
  Raven.setRequestContext(request, (error) => {
    // continue responding to request
  });
});
```

Right now I'm getting errors in Sentry but I'm missing loads of valuable context like which path are they requesting? With what data? Who's the user? (I know I'll have to do the last one on my own anyway). Thanks!

**Comment by kamilogorek** [comment]
You can already achieve it by using wrap/context methods – https://docs.sentry.io/clients/node/usage/#context-wrap

```js
http.createServer(Raven.wrap((request, response) => {
  Raven.setContext({ request: request });
  // continue
}));

or

```js
http.createServer((request, response) => {
  Raven.context(() => {
      Raven.setContext({ request: request });
      // continue
  });
});
```

Most (if not all) data you mentioned should be preserved and send through to Sentry.

**Comment by arasmussen** [comment]
Hey @kamilogorek, thanks for the quick response. But won't that also send a TON of other data that I don't need? That request object seems pretty huge.

It'd also be nice if there were a combined API for wrap + setContext. Separate issue though.

```es6
Raven.context({request: request}, () => {
  // continue
});
```

**Comment by kamilogorek** [comment]
No, it'll be stripped down to only those that we handle on the server :)
https://github.com/getsentry/raven-node/blob/master/lib/parsers.js#L59-L169

**Comment by arasmussen** [comment]
Smart, is that documented somewhere?

**Comment by arasmussen** [comment]
I didn't see it after reading this page https://docs.sentry.io/clients/node/ a few times. If it were in there somewhere, I'd definitely have done that instead of bugging you on this lovely Friday!

**Comment by kamilogorek** [comment]
It indeed was not. Fixed it https://github.com/getsentry/raven-node/pull/390 :)

**Comment by arasmussen** [comment]
Thanks! I just shipped the additional context for our site. Really looking forward to better server error context. Cheers!

**Comment by kamilogorek** [comment]
Cheers! :)
