### ISSUE TITLE
Raven.captureException does not process the request properly in Firebase Cloud Function Express app

### ISSUE THREAD

**Issue by mikemclin** [getsentry/raven-node#391]
I'm running an Express app via a Firebase Cloud Function.  I am able use `Raven.captureException(e)` successfully.  However, when I attempt `Raven.captureException(e, {req:req})`, I get an error.

I realize this seemed very similar to https://github.com/getsentry/raven-node/issues/375, so I also attempted to apply the fix, but still was experiencing issues (however receiving a different error stack).

### Error when 2.2.1 installed

```
TypeError: this.app.get is not a function
    at IncomingMessage.ip (/user_code/node_modules/express/lib/request.js:346:24)
    at /user_code/node_modules/raven/lib/client.js:545:19
    at Array.forEach (native)
    at /user_code/node_modules/raven/lib/client.js:544:15
    at Array.forEach (native)
    at Raven._createRequestObject (/user_code/node_modules/raven/lib/client.js:543:21)
    at Raven.process (/user_code/node_modules/raven/lib/client.js:239:22)
    at /user_code/node_modules/raven/lib/client.js:345:12
    at /user_code/node_modules/raven/lib/parsers.js:55:5
    at /user_code/node_modules/raven/lib/utils.js:259:5
    at /user_code/node_modules/raven/lib/utils.js:169:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

### Error when 31e58d31784033addc0a9e8374fbfe83776d5192 installed

```
TypeError: this.app.get is not a function
    at IncomingMessage.hostname (/user_code/node_modules/express/lib/request.js:424:24)
    at IncomingMessage.host (/user_code/node_modules/express/lib/request.js:447:14)
    at IncomingMessage.eval (eval at wrapfunction (/user_code/node_modules/express/node_modules/depd/index.js:411:42), <anonymous>:4:11)
    at /user_code/node_modules/raven/lib/client.js:580:19
    at Array.forEach (native)
    at /user_code/node_modules/raven/lib/client.js:579:15
    at Array.forEach (native)
    at Raven._createRequestObject (/user_code/node_modules/raven/lib/client.js:578:21)
    at Raven.process (/user_code/node_modules/raven/lib/client.js:240:22)
    at /user_code/node_modules/raven/lib/client.js:369:12
    at /user_code/node_modules/raven/lib/parsers.js:55:5
    at /user_code/node_modules/raven/lib/utils.js:259:5
    at /user_code/node_modules/raven/lib/utils.js:169:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

**Comment by samthecodingman** [comment]
In both cases, the error is from the same section of code [here](https://github.com/getsentry/raven-node/blob/master/lib/client.js#L567-L582).

In the first stack trace (v2.2.1), the error is thrown whilst evaluating the getter for `req.ip`. In the latest build, the error is being thrown by the getter for `req.host`, which has been wrapped by the deprecate package ([`depd`](https://www.npmjs.com/package/depd)).

The root of this problem likely stems from an odd situation where `source.app` is not the same as the express app that you are expecting. I would have thought that it might be a problem with the `this` context, but whatever `this` is has an `app` property. Furthermore, the property `request.app` isn't defined as non-enumerable, so that doesn't seem to be the cause.

I'm curious, what happens if you inject `'app'` as the first element of the array `nonEnumberables` on [line 568 of client.js](https://github.com/getsentry/raven-node/blob/master/lib/client.js#L568)?

**Comment by mikemclin** [comment]
When adding `'app'` to the list as seen here: https://github.com/mikemclin/raven-node/commit/f254a5da85df36d19054efc639bd76c00636f7f6, I get the same error as before.

```
TypeError: this.app.get is not a function
    at IncomingMessage.hostname (/user_code/node_modules/express/lib/request.js:424:24)
    at IncomingMessage.host (/user_code/node_modules/express/lib/request.js:447:14)
    at IncomingMessage.eval (eval at wrapfunction (/user_code/node_modules/express/node_modules/depd/index.js:411:42), <anonymous>:4:11)
    at /user_code/node_modules/raven/lib/client.js:581:19
    at Array.forEach (native)
    at /user_code/node_modules/raven/lib/client.js:580:15
    at Array.forEach (native)
    at Raven._createRequestObject (/user_code/node_modules/raven/lib/client.js:579:21)
    at Raven.process (/user_code/node_modules/raven/lib/client.js:240:22)
    at /user_code/node_modules/raven/lib/client.js:369:12
    at /user_code/node_modules/raven/lib/parsers.js:55:5
    at /user_code/node_modules/raven/lib/utils.js:259:5
    at /user_code/node_modules/raven/lib/utils.js:169:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

**Comment by kamilogorek** [comment]
Hey @mikemclin , it looks like @samthecodingman is right here, with this line:

> The root of this problem likely stems from an odd situation where source.app is not the same as the express app that you are expecting.

Express binds an `app` to every request object during initialisation, and it appears that you may override it somewhere.

Related code: https://github.com/expressjs/express/blob/master/lib/express.js#L46-L48

**Comment by mikemclin** [comment]
I was just getting ready to write that I don't think I am overriding the `app` anyewhere, and as I was pasting my code I noticed my `authMiddleware`.  I am defining the "app" DB record based on the auth credentials and overwriting the `request.app`.  I didn't realize `app` was already a defined property (my first express app).  I'm assuming that modifying this will fix the issue.  I will test and report back when I get home.

Here is the `authMiddleware.js`

```js
import { getAppByApiKey } from '../repos/apps';

export default async function authMiddleware(request, response, next) {
  const apiKey = request.get('x-paperstac-audits-key');
  if (!apiKey) {
    response
      .status(401)
      .json({
        message:
          '"x-paperstac-audits-key" was missing from the request headers.'
      });
    return;
  }
  const app = await getAppByApiKey(apiKey);
  if (!app) {
    response
      .status(401)
      .json({
        message: `Unable to find an app with the following apiKey: "${apiKey}".`
      });
    return;
  }
  request.app = app; // <-----THIS MUST BE THE ISSUE!!!!
  next();
}
```

**Comment by mikemclin** [comment]
My middleware was the issue.  Thanks!
