### ISSUE TITLE
Stripe errors not reported

### ISSUE THREAD

**Issue by FredrikNoren** [getsentry/raven-node#392]
This line seems to be the culprit (the stripe errors have a statusCode on them):
https://github.com/getsentry/raven-node/blob/31e58d31784033addc0a9e8374fbfe83776d5192/lib/client.js#L516

I'm not sure why that check is there in the first place, but figured I'd report this at least in case someone else runs into this.

Perhaps a simple fix is to make the check optional and off by default?

**Comment by kamilogorek** [comment]
It's because `errorHandler` shouldn't catch any `< 500` status code errors. Those should be handled manually by developers, as they vary per implementation (eg. 40X responses from Stripe).
