### ISSUE TITLE
Object [object Object] has no method 'getName'

### ISSUE THREAD

**Issue by DesignMonkey** [getsentry/raven-node#395]
Hello. When I call captureExeption from my Meteor node server I get this error, which gets my app to restart. 

```
TypeError: Object [object Object] has no method 'getName'
     at HTTPSTransport.HTTPTransport.send (/build/bundle/programs/server/npm/node_modules/raven/lib/transports.js:41:26)
     at /build/bundle/programs/server/npm/node_modules/raven/lib/client.js:310:22
     at Deflate.onEnd (zlib.js:167:5)
     at Deflate.emit (events.js:117:20)
     at _stream_readable.js:944:16
     at process._tickDomainCallback (node.js:492:13)
```

I think its when I call with the following command:

```javascript
Raven.captureException('getResult exeption', {
  extra: {
    settings: {
      resultId: '1234',
      tileId: '4567',
      timeView: 'year',
      timeElement: '2017',
      benchmarkId: 1,
      questionAlias: '187',
      bgVars: [],
      tileType: 'tileBarChart',
      navigationId: null,
      propertyViewId: null,
      sessionId: '7890',
    },
    error: 'Timeout: Request failed to complete in 30000ms',
  },
});
```

It also could be an uncaught Exception though.  

Does this make any sense? 

Im not sure how to debug this any further :/

**Comment by DesignMonkey** [comment]
Seems like the problem for is uncaught Exceptions, and Raven will force shutdown. Is there a way to avoid this behavior? And it still looks like that the uncaught Exception is from within Raven ( the getName function in transports.js:41

**Comment by kamilogorek** [comment]
What Node version are you using? `getName` is a method of `http.Agent` which comes from Node's standard library. It should always be accessible, unless `http` was somehow overridden.

**Comment by DesignMonkey** [comment]
I'm running node:0.10.41-slim in a Meteor environment in a Docker container.

Maybe I should look into a http polyfill for old node?

**Comment by kamilogorek** [comment]
You can just use `v2.1.2` instead, it should work just fine. Per our readme:

> The last known working version for v0.10 and v0.12 is raven-node@2.1.2. Please use this version if you need to support those releases of Node.

**Comment by kamilogorek** [comment]
Feel free to reopen if an issue still persists
