### ISSUE TITLE
Missing required attribute in authentication header: sentry_secret

### ISSUE THREAD

**Issue by Grmiade** [getsentry/raven-node#398]
I have this error when capture an error with `raven-node`
```
raven@2.2.1 alert: failed to send exception to sentry: HTTP Error (403): Missing required attribute in authentication header: sentry_secret
```

Sentry => hosted
raven-node => 2.2.1
node => 9.2.0 and 8.9.1

**Comment by mattgodbolt** [comment]
I'm also seeing this, using sentry.io public site, raven-node 2.2.1, node 8.9.0

**Comment by mattgodbolt** [comment]
Ok, it's not clear but you need to use the non-public DSN in configuring your app! That DSN has a long SHA then a colon, then another long SHA (public:private I guess). Then things seem to work!

**Comment by mattgodbolt** [comment]
Ah no. Now I get: 
Uncaught 
RavenConfigError
message
:
"Do not specify your secret key in the DSN. See: http://bit.ly/raven-secret-key"
name
:
"RavenConfigError"

The bitly URL isn't helpful.

**Comment by mattgodbolt** [comment]
(Note that if you're using both the server-side and client-side ravens, you mustn't use the private DSN on the client)

**Comment by kamilogorek** [comment]
Has this been resolved? Please feel free to reopen this issue if there is anything else.

**Comment by platan** [comment]
When I'm logged in documentation https://docs.sentry.io/clients/node/#configuring-the-client has a code snippet with secret key included. On the other hand, this part of the documentation (also for node.js) https://docs.sentry.io/clients/node/config/ has a code snippet without secret key.

**Comment by kamilogorek** [comment]
@platan this happens because we use dynamic code blocks on the former page. This will be unified soon.
