### ISSUE TITLE
Attach timestamp when capturing message

### ISSUE THREAD

**Issue by tmhpfnr** [getsentry/raven-node#404]
**Do you want to request a *feature* or report a *bug*?**

I want to request a **feature** / improvement

**Has someone had this problem before?**

Not that I know of.

**What is the current behavior?**

While performing a `raven.captureMessage` always the current timestamp is attached to the underlying `send` method.

**What is the expected behavior?**
It should be possible to pass a timestamp as key argument to adjust when the actual event happened like you already can with breadcrumbs.

**Comment by kamilogorek** [comment]
See: https://github.com/getsentry/raven-node/pull/405#issuecomment-356565953
