### ISSUE TITLE
Discarded invalid value for parameter 'logger' 

### ISSUE THREAD

**Issue by valeriangalliat** [getsentry/raven-node#406]
I'm getting the following error on all my Sentry events:

> Discarded invalid value for parameter 'logger' 

```
{
  "name": "logger",
  "value": ""
}
```

I never used the `logger` parameter, and it looks like the default value for `logger` as set by `raven-node` itself is `''`: https://github.com/getsentry/raven-node/blob/eb4695a6a7f36320f243611b28bf4597c9de614f/lib/client.js#L71

How to reproduce:

```js
require('raven').Client(process.env.SENTRY_DSN).captureException(new Error('Test'))
```

Outputs:

```js
{ message: 'Error: Tes',
  exception: [ { type: 'Error', value: 'Test', stacktrace: [Object] } ],
  user: {},
  tags: {},
  extra: {},
  breadcrumbs: { values: [] },
  request: {},
  modules: {},
  server_name: 'localhost',
  environment: '',
  logger: '',
  event_id: '...',
  timestamp: '2017-12-06T20:57:31',
  project: '...',
  platform: 'node' }
```

And the "Discarded invalid value for parameter 'logger'" is present on Sentry.

Thank you :)

**Comment by kamilogorek** [comment]
Thanks for the report @valeriangalliat. We made some changes to sentry UI recently. I'll take care of it.
