### ISSUE TITLE
raven@2.2.1 alert: failed to send exception to sentry: unable to get local issuer certificate 

### ISSUE THREAD

**Issue by awesomehimanshu** [getsentry/raven-node#410]
bug 

**raven@2.2.1 alert: failed to send exception to sentry: unable to get local issuer certificate**

I have added raven like this 

> global.Raven = require("raven");
> Raven.config(APP_CONFIG.sentryServerURL, {sendTimeout: 5}).install();

I was using the raven for node.js it was working fine but i am getting error now.

But now it is given error when i run .

>  Raven.captureException(data, {req: req});

Raven version : raven@^2.1.0
OS : windows 7
NODE : 6.10.2
**what is the cause ?**

**Comment by awesomehimanshu** [comment]
Any update on this ? what would be causing this ?

**Comment by kamilogorek** [comment]
It's an SSL issue. Are you using on-premise installation or our https://sentry.io/ instance?

**Comment by awesomehimanshu** [comment]
I have used sentry from here .
https://docs.sentry.io/clients/node/ .


code in app.js is something .

global.Raven = require("raven");
Raven.config(APP_CONFIG.sentryServerURL, {sendTimeout: 5}).install();

// this for capture the error when occur .
Raven.captureException(err, {req: req});

**Comment by kamilogorek** [comment]
I mean do you use https://sentry.io or your own instance using https://github.com/getsentry/sentry repository, not SDK itself.

**Comment by Anubhavgarg** [comment]
Any update on this issue. Same issue I am facing

**Comment by kamilogorek** [comment]
I don't have enough information to help here. Please read my previous questions.

**Comment by kamilogorek** [comment]
Closed due to inactivity

**Comment by awesomehimanshu** [comment]
It is working . This issue has to do with authentication issue of network, not related to this repo .
