### ISSUE TITLE
When there is Error, how to display more information by sentry?

### ISSUE THREAD

**Issue by Sean-Wang** [getsentry/raven-node#415]
I have added sentry in the NodeJs(Express). When  there is abnormal situation, I can receive relevant information in time. It is very useful. 

But I hope sentry can collect more information of all api mistakes. For example, current api’s request parameters. Is it possible to be implemented? Please let me know how to configure. 

Thanks.

Now sentry configuration of index.js as follows:

```javascript
var Raven = require ('raven');
var ravenClient = new Raven.Client('https://xxxxxx@sentry.io/xxxxxx', {
    environment: process.env.NODE_ENV
}).install();
```

**Comment by kamilogorek** [comment]
Sure it is possible :) please refer to integration docs here https://docs.sentry.io/clients/node/integrations/express/

Feel free to reopen if something goes wrong, however if you have any questions regarding how things work, please point them here https://forum.sentry.io/

Cheers!
