### ISSUE TITLE
Stacktrace is showing compiled code and not the original source.

### ISSUE THREAD

**Issue by bilby91** [getsentry/raven-node#418]
**Do you want to request a *feature* or report a *bug*?**
Potencial bug

We are migrating our error tracking to Sentry from Airbrake due to the new sourcemaps support for NodeJS.

So far we’ve been able to create a release and upload all the artifacts using sentry-cli. Everything works correct except for the rendering of the code in the sentry web interface, it shows the compiled javascript instead of the typescript code. The strange thing is, the snippet references the typescript file and not the javascript file.

Any ideas of what we could be missing ?

**Has someone had this problem before?**

No related issue that I could find.

**What is the current behavior?**

The stacktrace is showing the compiled code.

**What is the expected behavior?**

The stacktrace should show the source code instead of the compiled code.

**Comment by kamilogorek** [comment]
Are you able to provide minimal repro case with your code and config that I could use to investigate this issue?

**Comment by bilby91** [comment]
Thanks @kamilogorek !

Yes, this is my reporter wrapper class that hold all the interaction with `raven`.

```
import { Client, DataCallback } from "raven"
import { IErrorReporter } from "./interface"

const directoryPrefix = "/var/www/app/dist/"

const dataCallback: DataCallback = (data) => {
  const stacktrace = data.exception && data.exception[0].stacktrace

  if (stacktrace && stacktrace.frames) {
    stacktrace.frames.forEach((frame: any) => {
      if (frame.filename.startsWith(directoryPrefix)) {
        const transformedFilename = frame.filename.slice(directoryPrefix.length)

        frame.filename = "app:///" + transformedFilename
      }
    })
  }

  return data
}

export class SentryReporter implements IErrorReporter {
  private client: Client

  constructor(dsn: string) {
    this.client = new Client(dsn, {
      captureUnhandledRejections: true,
      dataCallback,
      release: process.env.GIT_REV,
    })
  }

  public install() {
    this.client.install()

    return this
  }

  public notify(error: Error, params?: any) {
    this.client.captureException(error, {
      extra: params,
    })
  }

  public requestHandler() {
    return this.client.requestHandler()
  }

  public requestErrorHandler() {
    return this.client.errorHandler()
  }
}
```

**Comment by kamilogorek** [comment]
Thanks, I'll try to take a look at this soon. Will get back to you.

**Comment by bilby91** [comment]
@kamilogorek Thanks! We are eagerly waiting for an answer :)

**Comment by kamilogorek** [comment]
Can you show me how it looks for you in Sentry dashboard? Or a link to a specific issue?

I was able to properly render everything using your reporter implementation and our webpack plugin – https://github.com/getsentry/sentry-webpack-plugin

<img width="426" alt="screen shot 2018-01-22 at 12 02 21" src="https://user-images.githubusercontent.com/1523305/35217606-2e829780-ff6c-11e7-81cc-a30a41de58ff.png">

**Comment by bilby91** [comment]
@kamilogorek Can you give me an email address so I can send you some attachments ?

Thanks!

**Comment by kamilogorek** [comment]
@bilby91 pinged you on your github email

**Comment by kamilogorek** [comment]
Solved w. usage of https://github.com/getsentry/raven-node/pull/419
