### ISSUE TITLE
setExtraContext is not a function

### ISSUE THREAD

**Issue by saiichihashimoto** [getsentry/raven-node#420]
When using `Raven.context` or `Raven.wrap`, the wrapped function doesn't have access to `setExtraContext`, `setUserContext`, or any of the methods [it's supposed to have](https://docs.sentry.io/clients/node/usage/#context-wrap). Actually, when searching this codebase, I can't find [setExtraContext anywhere](https://github.com/getsentry/raven-node/search?utf8=%E2%9C%93&q=setExtraContext&type=). What's going on here?

**Comment by kamilogorek** [comment]
Those methods were removed from `raven-node` and associated together in favor of `set/get/mergeContext` – https://github.com/getsentry/raven-node/blob/c94b6d4cf9df994eef707e84c4ecf83921d368b1/History.md#100---12122016
It'll be reworked in the next major version.
