### ISSUE TITLE
Organisation prefixed npm package versions not shown

### ISSUE THREAD

**Issue by adamreisnz** [getsentry/raven-node#423]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**Has someone had this problem before?**
Nope, couldn't find anything.

**What is the current behavior?**
Organisation prefixed npm package versions are not reported in the list of package versions when an error is reported, e.g. `@sendgrid/mailer`, `@meanie/express-errors`.

![image](https://user-images.githubusercontent.com/490562/35772754-485ef9dc-09a8-11e8-9357-532bd62c36f2.png)

They also don't appear under `m` or `e`.

**What is the expected behavior?**
For organisation prefixed/namespaced packages to also appear.

Raven ^2.3.0

**Comment by kamilogorek** [comment]
Thanks. We are using https://github.com/defunctzombie/node-lsmod for this right now, which is slightly outdated. I'll take a look at it when I find some time.

**Comment by kamilogorek** [comment]
Released as `2.4.1`
