### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by juliocanares** [getsentry/raven-node#432]
**Has someone had this problem before?**

Nope

**What is the current behavior?**

I am running multiple tests with Jest and when sentry is enabled this warning shows up.

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
```

**What is the expected behavior?**

not to show these warnings.

**Comment by kamilogorek** [comment]
What's your test setup? It should be an issue of sandboxing your "per test" environment, as it looks like you're installing Raven multiple times when running your tests.

**Comment by juliocanares** [comment]
this my jest config.

```js
module.exports = {
  verbose: true,
  testEnvironment: 'node',
  setupTestFrameworkScriptFile: './__tests__/setup.js',
  testPathIgnorePatterns: [
    '/node_modules/',
    './dist/',
    '<rootDir>/__tests__/'
  ],
  coverageReporters: [
    'lcov',
    'html'
  ]
}
```

I have a sentry.js file

```
import raven from 'raven'

raven.config(process.env.SENTRY_DSN, {
  environment: process.env.NODE_ENV,
  captureUnhandledRejections: true
}).install()

export default raven
```

which is call when the server is started.

```
import { sentry } from 'connectors'

if (process.env.NODE_ENV === 'production') {
  app.use(sentry.requestHandler())
}
```


this is also call when an error needs be to reported
```
import { sentry } from 'connectors'

  debug('error', error)

  if (process.env.NODE_ENV === 'production') {
    const context = assign(
      sentry.parsers.parseRequest(req),
      { user }, { tags }, { extra }
    )

    if (error.path || error.name !== 'GraphQLError') {
      context.graphql = 'exec_error'
      return sentry.captureException(error, context)
    }

    context.graphql = 'wrong_query'
    sentry.captureMessage(`GraphQLWrongQuery: ${error.message}`, context)
  }
```

If you see I only call sentry methods in production, but this even fails in test and development environment.

any thoughts?

**Comment by juliocanares** [comment]
any help on this? @kamilogorek

**Comment by kamilogorek** [comment]
@juliocanares sorry, I was sick for the last 3 days. I'll try to take a look at it tomorrow morning.

**Comment by juliocanares** [comment]
hope you are better, let me know when you have something @kamilogorek 😄

**Comment by kamilogorek** [comment]
Is there a chance that you could provide repro-case with bare minimum code that creates this issue? What probably happens, is that Jest (or maybe something else?) somehow make imports not being a singleton, and every time it creates a new instance instead: https://github.com/getsentry/raven-node/blob/master/lib/client.js#L653-L658

This on the other hands allows for installing multiple handlers here: https://github.com/getsentry/raven-node/blob/master/lib/client.js#L121-L123

by going around `this.installed` check, as it's not the same instance https://github.com/getsentry/raven-node/blob/master/lib/client.js#L113

This shouldn't really happen and looks strange, but it's my best guess for now.

As a quick test for this, you can call

```js
afterEach(() => {
  global.process.removeAllListeners('unhandledRejection');
})
```

or even better, if you have an access from the tests

```js
import { sentry } from 'connectors'

afterEach(() => {
  sentry.uninstall()
})
```

in your tests and it should resolve the issue (which doesn't mean it's the solution to the problem! just a quick check if this is an actual issue :))

**Comment by juliocanares** [comment]
just tried jest `22.4.2` it works like a charm, no modifications needed 👍
