### ISSUE TITLE
Add ability to clear breadcrumbs

### ISSUE THREAD

**Issue by killroyboy** [getsentry/raven-node#448]
I add breadcumbs of data while processing certain tasks within a loop. Once that task is completed, I would like to be able to clear the breadcrumbs so when an exception occurs (or I capture manually), I only have the data relevant to the current iteration of the task.

As far as I could see there is no API to clear the current breadcrumbs. Am I mistaken?

**Comment by kamilogorek** [comment]
There's no direct API method for doing that, but because breadcrumbs are just a part of the context, you can either use:

```js
Raven.setContext(Object.assign(Raven.getContext(), {
  breadcrumbs: []
});
```

or `mergeContext` method which *is* available and is basically the same thing underneath

```js
Raven.mergeContext({ breadcrumbs: [] });
```

**Comment by killroyboy** [comment]
Thanks!
