### ISSUE TITLE
Also report node version(s)

### ISSUE THREAD

**Issue by djmitche** [getsentry/raven-node#449]
Lots of issues, unfortunately, are related to node bugs.  I would like to see the node version (and maybe everything from `process.versions`) somewhere in an error report.

I think the easiest way for me to accomplish this is to add it to `data.modules` in a `dataCallback`, but it would be far better if raven added this information itself.

Is `modules` the best property to use?

I can work on a PR for this if the idea would be accepted.

**Comment by kamilogorek** [comment]
Hey @djmitche, we are already doing that :)

https://github.com/getsentry/raven-node/blob/master/lib/client.js#L268-L270

<img width="504" alt="screen shot 2018-04-12 at 19 10 48" src="https://user-images.githubusercontent.com/1523305/38692815-43b40dd4-3e85-11e8-8c8d-aae43a0d644f.png">

**Comment by djmitche** [comment]
Oh, that's embarassing -- I thought I was using the latest version of `raven` but I am most decidely not.  *sorry*!
