### ISSUE TITLE
Feature Request | Allow Multiple Raven Instances

### ISSUE THREAD

**Issue by steverice** [getsentry/raven-node#459]
**Do you want to request a *feature* or report a *bug*?**

feature

**Has someone had this problem before?**

This is the same feature described in https://github.com/getsentry/raven-js/pull/1269, but a request that it be available in `raven-node`.

To recap:
Our node server executes code that is is affected by other services from multiple teams. Each of these services is developed and managed independently. Each team wants to have a separate DSN so their errors can be monitored separately. At the same time, we have a Raven singleton that captures any uncaught errors (those that are not captured explicitly with `captureException`).
Unfortunately, the current API doesn’t allow this.

Currently, we accomplish this with some messy manipulation of Raven's internals. _Roughly_,
```javascript
const makeRaven = () => {
  const raven = new RavenFactory();
  raven.prototype = RavenFactory.prototype;
  raven.version = Raven.version;
  raven.disableConsoleAlerts = Raven.disableConsoleAlerts;
  raven.utils = ravenUtils;
  raven.transports = ravenTransports;
  raven.parsers = ravenParsers;
  return raven;
};

Object.keys(sentryConfigs).forEach((key) => {
  const ravenConfig = sentryConfigs[key];
  if (key === 'main') {
    const dsn = ravenConfig.dsn;
    // Must configure Raven before doing anything else with it
    Raven.config(dsn, ravenConfig).install();
    // The request handler must be the first middleware on the app
    expressServer.use(Raven.requestHandler());
  } else {
    const extraRaven = makeRaven();
    extraRaven.config(dsn, ravenConfig); // don't install because this shouldn't catch unhandled errors
    Raven._extraRavens = Raven._extraRavens || {};
    Raven._extraRavens[key] = extraRaven;
  }
});
```

and then we use these by calling `Raven._extraRavens[projectName].captureException()`.

Obviously, this isn't the greatest or most stable solution. API support for this such as added in https://github.com/getsentry/raven-js/pull/1272 would be much preferred.

**Comment by kamilogorek** [comment]
Hey @steverice, it's already possible :)

https://docs.sentry.io/clients/node/usage/#multiple-instances

Cheers!

**Comment by steverice** [comment]
Fantastic, thanks @kamilogorek !
