### ISSUE TITLE
Limit private data being sent

### ISSUE THREAD

**Issue by moll** [getsentry/raven-node#49]
Hello,

Raven sends awfully lot of requests' private data (and thereby private data of people) to Sentry, which frankly it mustn't.

Fortunately reimplementing the Connect middleware is not too difficult, but there are bits of data gathering that are not possible to overwrite without changing the source. `LINES_OF_CONTEXT` that grabs the contents of the source files is one of those bits. If anything, that should be set as a property in some Raven object that would make it possible to disable source sending entirely.

**Comment by LewisJEllis** [comment]
At the moment this is possible via the `dataCallback` config option documented [here](https://docs.sentry.io/hosted/clients/node/config/). Specifically look at modifying or removing `data.exception[0].stacktrace`, which is an object with a `frames` property which is an array of frame objects that each look something like:
```javascript
{
  filename: '/Users/lewis/dev/express-demo/index.js',
  lineno: 48,
  function: 'null.<anonymous>',
  in_app: true,
  module: 'index',
  pre_context: ['previous', 'lines', 'of', 'code'],
  context_line: '  throw new Error(\'oh no an error!\');',
  post_context: ['following', 'lines', 'of', 'code']
}
```

I'll add an item to the roadmap to create a more easily configurable filter to do this like [Raven::Processor::RemoveStacktrace](https://github.com/getsentry/raven-ruby/wiki/Advanced-Configuration#sanitizing-data-processors) from raven-ruby.
