### ISSUE TITLE
Provide way to attach user information when capturing

### ISSUE THREAD

**Issue by ehd** [getsentry/raven-node#54]
It's useful to know which user and how many users caused an error, especially because Sentry can turn that information into a useful metric.

The problem in node is that there exists no concept of "the current user". It makes no sense.

It's already possible to attach user info when capturing an error:

``` js
client.captureError(error, {
  'sentry.interfaces.User': {
    id: 'foobar'
  }
});
```

It wouldn't make much sense to provide a `client.setUser` method like in raven-js. The client is probably shared among different requests with separate users. So I suggest adding a shorthand for this:

``` js
client.captureError(error, {
  user: {
    id: 'foobar'
  }
});
```

Another idea was allowing something like this:

``` js
var userClient = client.forUser(currentUser);

// Somewhere else
userClient.captureError(error); // <--- includes user information
```

**Comment by LewisJEllis** [comment]
Context issues around this have been resolved in recent work/upcoming release.
