### ISSUE TITLE
Implement processors/sanitization API

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-node#59]

**Comment by andyuk** [comment]
Yes please - I'd like this feature. Security should be top priority. Obviously not the case here. Free coffee for first person to issue a pull request for this.

**Comment by dcramer** [comment]
While not ideal, data still gets scrubbed on the server.

I would -1 our existing processors API as its kind of shitty, and really what we want to do is just have a set of commands that take the data input and give the data output.

**Comment by SimonSchick** [comment]
You can use `shouldSendCallback` to do scrubbing, it gets passed all log data by reference.

**Comment by SimonSchick** [comment]
Oh god I just noticed how old this issue is, @dcramer shouldn't this be closed considering there is `dataCallback`?

**Comment by dcramer** [comment]
@SimonSchick thanks! we're not great at managing all of our issue trackers yet today :/
