### ISSUE TITLE
Ignore undefined values

### ISSUE THREAD

**Issue by brunoduran** [getsentry/raven-node#61]
As a suggestion, It think it would be a nice feature that the function `captureError` and family would ignore the `undefined` or `null` values. It would allow to make a cleaner use of the client.

Right now it's impossible to call the function directly like this: 

```javascript
functionWithCallback(a,b,c, client.captureError);
```

And force the use of an additional functions:

```javascript
functionWithCallback(a,b,c, function(e){ if(e) client.captureError(e); });
```

Regards,
Bruno

**Comment by benvinegar** [comment]
Since nobody has chimed in on this in > 2 years, going to close. I agree w/ @defunctzombie – this is easily solved by just writing your own quick wrapper function.
