### ISSUE TITLE
send callback

### ISSUE THREAD

**Issue by kof** [getsentry/raven-node#7]
hi
1. captureMessage, captureError etc. callbacks should be fired after the message is delivered
2. sendRemote ignores errros, which actualy should be passed to the callback. Please pass the error object also if emiting error on client instance         self.emit('error', err);

If I want to log something and then exit the process, I need this send callback, otherwise I have to do ugly setTimeout for some time to ensure the message was sent.

**Comment by christophercliff** [comment]
I was having a similar issue so I created a new client with a node-compatible API: https://github.com/christophercliff/sentry-client

It's easier to implement the log-and-exit approach.
