### ISSUE TITLE
Same object in different interfaces ignored

### ISSUE THREAD

**Issue by moll** [getsentry/raven-node#91]
Hey,

The circular dependency checking code in `client.js` is a little naíve and strips every duplicate object. Not to mention it's rather inefficient. It really should ignore only circular dependencies, not merely objects appearing twice in two different places. Just spent some wtfs trying to figure out why headers in the HTTP interface were ignored. They were intentionally both on the error object and the HTTP interface.

**Comment by moll** [comment]
Not even a year has passed and I got around to it!
Please see https://github.com/isaacs/json-stringify-safe and https://github.com/isaacs/json-stringify-safe/issues/9 for a proper circular `JSON.stringify`. Thanks!

**Comment by benvinegar** [comment]
Implemented json-stringify-safe in #182.
