### ISSUE TITLE
Handle http 429? 

### ISSUE THREAD

**Issue by MaerF0x0** [getsentry/raven-node#95]
I came here to get ideas about how you handle the promised (threatened?) [HTTP 429 for throttling](https://www.getsentry.com/docs/quotas/). Was surprised not to find it anywhere in the code base, seems >299 is treated as an error. Thoughts on maybe doing a warning or wait and retry?

**Comment by kamilogorek** [comment]
This issue has been closed due to over a year of inactivity. If anyone feels that it should be reopened, please feel free to reopen it and letting me know. Thanks.
