### ISSUE TITLE
Express deprecation warning for `req.host`

### ISSUE THREAD

**Issue by clayzermk1** [getsentry/raven-node#96]
> express deprecated req.host: Use req.hostname instead node_modules/raven/lib/parsers.js:84:19

Messages are showing up in the log for Express 4.9.5.

If I get around to it, I'll cook up a trivial PR and give it some testing love.

Cheers!

**Comment by Ajar-Ajar** [comment]
"express deprecated req.host: Use req.hostname instead ... node_modules/raven/lib/parsers.js:84:19
very easy to fix - I swapped it locally but every time I install the package it throws this error again - please change it. simply replace req.host with req.hostname like the error message suggests.
Thanks
Ajar

**Comment by oliviertassinari** [comment]
This issue resurfaced with this change https://github.com/getsentry/raven-node/commit/5d8556aba2682c8add539a77a8b8f35ae3116797. cc @kamilogorek looks like you recently joined the organization.

**Comment by kamilogorek** [comment]
This is just a warning, not an issue. It'll also never break anything and a change mentioned here https://github.com/getsentry/raven-node/commit/5d8556aba2682c8add539a77a8b8f35ae3116797 is required for some other frameworks.
Is this changing anything for you other than the additional line of text in the logs?

**Comment by oliviertassinari** [comment]
> Is this changing anything for you other than the additional line of text in the logs?

It's not an additional line of text in the logs. It's the first warning we have. It's a noise that will weaken future important warning messages.

**Comment by yegortokmakov** [comment]
guys, please release it

**Comment by kamilogorek** [comment]
@yegortokmakov released as `2.4.0`
